mfontanini/presenterm

src/builder.rs

This ignores HTML comments that contain nothing but a vim-like code folding tags (`{{{` and `}}}`).
Fixes #23

Ignore vim-like code folding tags

---

themes/light.yaml

Add light theme

---

README.md

I've updated the Nix section, so it explains the different options for Nix user, while still retaining the information on how to use the repo's own flake file. I don't know how familiar you're with Nix, so thought it would be easier, I proposed an addition to the README.md.

Update information on using the Nix package

---

src/export.rs

After the introduction of colorless themes (#68) the PDF export currently breaks if you use that (the PDF looks all compacted). Now, I could fix this in presenterm-export so it doesn't look all compacted. However, the background color will be the default browser background color which is probably white and therefore your presentation will look terrible. This instead makes the code fail early so we don't even attempt to generate the PDF if you use that; you should pick a theme that uses specific background colors instead.

Don't allow no background/foreground colors on PDF export

---

themes/dark.yaml
themes/light.yaml
themes/terminal-dark.yaml
themes/terminal-light.yaml
themes/tokyonight-storm.yaml

This makes formulas look better depending on built-in themes.

Adjust themes' colors for typst rendering

---

.editorconfig
bat/update.sh
bat/verify.sh

Format .sh files and add .editorconfig so shfmt picks it up.

Edd .editorconfig for *.sh and format shell scripts

---

src/builder.rs

[![asciicast](https://asciinema.org/a/4Qp8JHoTSZNuxxm4cp0kunt40.svg)](https://asciinema.org/a/4Qp8JHoTSZNuxxm4cp0kunt40)
Fixes #84

Add comment command to jump to vertical middle

---

src/builder.rs

The changes in #87 did not consider the front matter and added a new slide when it was present. This fixes that.
Fixes #65 for reals

Don't add new slide when front matter is present

---

docs/pdf-export.md

This was found to be an issue in #97.

Add note about weasyprint in exporter docs

---

src/builder.rs

This allows having automatic list pauses by using the `incremental_lists: true` comment command.
Fixes #105

Allow enabling automatic list pauses

---

src/builder.rs

This makes the changes in #105 work for nested lists.

Make incremental lists work with nested lists

---

src/builder.rs
src/main.rs

This prioritizes the theme passed via `--theme` over anything else. This means no matter whether your presentation defines the theme to be used or you have a default one in your config file, this will take priority. Note that you can still override the `--theme` within the presentation; this only affects the "base" theme in use.

Prioritize CLI args theme over anything else

---

.github/dependabot.yml
Cargo.lock
Cargo.toml

This needs to be configured using groups as it's way too noisy otherwise. Bump everything manually for now.

Update dependencies and disable dependabot

---

src/input/fs.rs

Don't blow up if presentation file temporarily disappears

---

src/markdown/parse.rs

Parse front matter properly in presence of \r\n

---

Cargo.lock
Cargo.toml
src/markdown/parse.rs

This was recently added to comrak so we now support it as well.

Add support for multiline block quotes

---

src/media/ascii.rs

This blends semi-transparent image pixels when using ascii-blocks mode with the background color. This creates a slightly better looking image as it will otherwise have unexpected colors around its edges.
Left: now, right: before

Blend ascii blocks image semi-transparent borders

---

src/processing/builder.rs

This affects the `end_slide_shorthand` option: a newline was being added at the beginning of every slide.

Don't add an extra line after an end slide shorthand

---

src/input/user.rs

This adds the f keys (via `<f1>` ... `<f12>`), `tab` and `backspace` as valid key bindings.

Add f keys, tab, and backspace as possible bindings

---

docs/src/guides/themes.md

Adds updates to the docs for the [newest catppuccin themes](https://github.com/mfontanini/presenterm/pull/205)

Update docs to include all catppuccin themes

---

src/presenter.rs

This was introduced previously on #118.

Don't crash in present mode

---

executors/C.sh
executors/Cpp.sh
executors/Go.sh
executors/Java.sh
executors/JavaScript.sh
executors/Lua.sh
executors/Perl.sh
executors/Ruby.sh
executors/Rust.sh

This allows executing code in C, C++, go, Java, js, lua, perl, ruby, and rust. It's not a huge list but it's _something_.

feat: allow executing code in various languages

---

docs/src/guides/basics.md

docs: document multiple authors in intro slide

---

src/markdown/elements.rs
src/render/highlighting.rs

Fix the support for nushell on linux
_However nushell still doesn't work on windows because of the way the executor works_

Fix support nushell

---

src/processing/builder.rs
src/processing/execution.rs

This adds a little banner when a `+exec` code snippet is executed but code execution is disabled, as it otherwise just silently does nothing.

feat: show a message if code is executed but execution is disabled

---

src/export.rs

After the changes to render `+render` blocks asynchronously, PDF generation was broken as it wasn't a) polling the renders and b) inspecting the renders to see if there were any images in it.

fix: poll + inspect async renders when generating PDF

---

src/main.rs
src/presentation.rs
src/presenter.rs

Code snippet output was not being included in the output PDF.

feat: include code snippet execution output in generated PDF

---

src/presenter.rs

When on an error screen (e.g. an invalid image path is specified) this currently explodes when you resize the terminal.

fix: don't crash on resize when displaying an error

---

src/export.rs

Async renders are waited on when export mode starts so without this presenterm-export could miss the first few slides when using mermaid.

fix: wait for all async renders during export at beginning

---

src/presenter.rs

After a recent change, resizing the window after an overflow was found would never re-check whether the overflow was fixed.

fix: re-check for overflows after resize

---

Cargo.lock
Cargo.toml
config-file-schema.json
config.sample.yaml
src/custom.rs
src/input/source.rs
src/input/user.rs
src/presenter.rs
src/render/draw.rs
src/render/terminal.rs

Hello!
Closes #237 
This PR allows `presenterm` to be suspended / resumed with `<c-z>` and `fg`.
Thanks!

feat: handle suspend signal (SIGTSTP)

---

executors.yaml
src/execute.rs
src/main.rs
src/presenter.rs

Intends to fix #322
I mostly just quickly wrote something so it would work for my use-case, so I didn't test all languages.
---

fix: execute script relative to current working directory

---

src/main.rs

fix: canonicalize resources path

---

executors.yaml
src/processing/code.rs

Hello!
This adds the ability to execute PHP code.
Thanks!

feat: add php executor

---

docs/src/guides/code-highlight.md

Just adding some docs for this ability, thanks!

docs: document `all` keyword

---

examples/README.md
examples/columns.md

docs: add example on how column layouts and pauses interact

---

src/processing/builder.rs

fix: handle inline code in block quotes

---

src/diff.rs
src/presentation.rs
src/processing/builder.rs
src/processing/code.rs
src/processing/execution.rs
src/processing/separator.rs
src/render/engine.rs
src/render/text.rs

fix: show block quote prefix when wrapping

---

src/processing/separator.rs

fix: don't wrap separator line

---

src/main.rs

This was broken on a recent change

fix: allow list-themes/acknowledgements to run without path

---

src/main.rs

Closes https://github.com/mfontanini/presenterm-export/issues/11

fix: pass along -X to presenterm-export

---

src/processing/code.rs
src/render/highlighting.rs

Adding GraphQL code highlighting.
`bat` is so awesome 😮

feat: add graphql code highlighting

---

src/ansi.rs
src/diff.rs
src/markdown/elements.rs
src/markdown/parse.rs
src/markdown/text.rs
src/presentation.rs
src/processing/builder.rs
src/processing/code.rs
src/processing/execution.rs
src/processing/modals.rs
src/processing/separator.rs
src/render/draw.rs
src/render/engine.rs
src/render/highlighting.rs
src/render/text.rs
src/resource.rs
src/third_party.rs

This cleans up a few things around constructing styles, line numbers when displaying errors, etc.

refactor: misc cleanups

---

executors.yaml

Added Haskell executor

---

src/presentation/builder.rs

This allows multiline speaker notes, but also multiline comment commands in general. The conditions here are changed so that we first try to parse a comment command and if that fails we then check if we should ignore it. This allows essentially using any comment command in a multiline fashion, such as:
```markdown
```
and
```markdown
```

feat: allow multiline speaker notes

---

src/markdown/parse.rs

This adds wikilinks support via the `[[url]]` syntax.
Relates to #447

feat: add support for wikilinks

---

src/terminal/capabilities.rs

This fixes an issue where we're inside tmux but `allow-passthrough` is disabled, which manifests in presenterm getting stuck on startup because tmux never forwards the escape codes sent to query for terminal capabilities to the terminal, hence we never get an answer. The fix here is to spawn a thread that will wait a second and if after that time we still haven't received an answer it will make a device status report query without the passthrough prefix, meaning tmux (if under tmux) will answer it, and will wake the main thread up.
Fixes #455

fix: don't get stuck if tmux doesn't passthrough

---

src/theme/raw.rs

After the change to allow images in footers, the error message when the footer is malformed was useless. This implements a custom deserializer to have proper error messages since the derive macro was getting confused.

fix: show meaningful error if footer is broken

---

src/presentation/builder/mod.rs

This adds an `alignment` comment command that can have a left/center/right values. This uncovered a few issues in how some elements (e.g. lists in particular, but also normal text) render with center/right alignment, but they'll be fixed separately.
Fixes #492

feat: add alignment comment command

---

.github/workflows/nightly.yaml

This adds a nightly job that builds the latest source code and uploads it to "pre-release" release.

ci: add nightly build job

---

src/presentation/builder/mod.rs

This adds a new `skip_slide` comment command that allows skipping that slide and not including it in the final presentation.
Fixes #502

feat: add `skip_slide` command

---

.github/workflows/nightly.yaml
.github/workflows/release.yaml

This changes the nightly and release builds to enable sixel support.

ci: build with sixel enabled

---

src/terminal/virt.rs

fix: respect line height when jumping lines when rendering PDF

---

src/markdown/elements.rs
src/presentation/builder/mod.rs

Regression introduced in #512. This + inline code needs something more robust.
Fixes #521

fix: respect font size in lists

---

src/terminal/capabilities.rs

fix: show error if sixel mode is selected but disabled

---

src/presentation/builder/mod.rs

This fixes an issue where a presentation with a `theme.path` in the front matter that pointed to a theme that contained an `extends` wouldn't have its `extends` respected.

fix: respect `extends` in a theme set via `path` in front matter

---

src/presentation/builder/mod.rs

Headings were being added an extra space if they had an empty string configured as the prefix. This worked correctly if the prefix was `null` but not if it was "".
Fixes #541

fix: don't add extra space before heading if prefix is empty

---

README.md

It turns out I'm a heavy user of _presenterm_!
I only added my presentations - let me know if you know of any others I should add.
closes #538

docs: add links to presentations using presenterm

---

src/presentation/builder/snippet.rs

This causes `+exec_replace` blocks to have no margin when using center alignment. This is a regression introduced somewhere in 0.12.0.
Fixes #571

fix: truly center `+exec_replace` snippet output

---

src/ui/footer.rs

This allows including spans that contain variables in footers. This does mean that if you pull in a variable like `{title}` that contains `<` or `>` it will be included as-is and would allow creating valid HTML tags, but this is harmless so I don't see a problem with it.
Fixes #574

fix: allow interleaved spans and variables in footer

---

README.md

I used presenterm for my presentation on [Pentester Nepal](https://pentesternepal.com)'s 11th anniversary. I'm providing source to my slides.

feat(docs): demo talk using presenterm

---

src/render/ascii_scaler.rs
src/render/engine.rs
src/render/text.rs
src/terminal/printer.rs
src/terminal/virt.rs

fix: avoid printing text if there's no vertical space for it

---

src/presentation/builder/mod.rs

fix: properly skip slides with pauses

---

src/terminal/printer.rs

This uses OSC 11 to set the background color, when an RGB color is used, so that the ugly borders that terminals add when the screen is not an exact multiple of the cell size is used.
Fixes #615

fix: set background color via OSC 11

---

src/presentation/builder/mod.rs

fix: skip speaker notes slide on `skip_slide`

---

src/terminal/printer.rs

Another fixup for #624 so we only use this when clearing the screen.

fix: only use OSC 11 on clear screen

---

src/markdown/parse.rs

This displays an explicit error when trying to use a http(s) URL in an image tag.

chore: display an error when using http(s) URLs in image tags

---

src/code/highlighting.rs

fix: consider color range 0x08.. - 0x0f.. in bat themes

---

executors.yaml

This adds the language Elixir to the executors

Add Elixir to executors

---

src/presentation/builder/heading.rs

Fix a bad interaction between #738 and #739.

fix: don't consider prefix part of the title

---

config.sample.yaml

fix: use `show_pauses` in sample config
