mfontanini/presenterm

.github/releaser.sh, .github/workflows/release.yml, Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs, src/splash.rs
HelloW,  You got a really nice project there. Congrats on that :clinking_glasses: 
This pr will allow you to use github actions and release binaries of `presenterm` .
Few notes :
1. Don't forget to add `CARGO_TOKEN` as secret before merge for [`crates.io`](https://crates.io) releases
2. Consider adding a `CHANGELOG.md`, You can use [`git-cliff`](https://git-cliff.org) for that. I'm not super familiar with this but still you can get some idea from my [`repos`](https://github.com/pwnwriter)
3. Allow github actions to publish 
----
Image -> 
---- 
The process would go like this . Tested [`here`](https://github.com/pwnwriter/presenterm/releases)
4. I added `cargo` profiles for `release,bench,test,dev`. It was helping me a lot to minimize the binary size and test with minimal efforts. 
Feel …
=> feat(release): Use github actions to release binaries

.github/PKGBUILDS/presenterm-bin/.SRCINFO, .github/PKGBUILDS/presenterm-bin/PKGBUILD, .github/PKGBUILDS/presenterm-git/.SRCINFO, .github/PKGBUILDS/presenterm-git/PKGBUILD, README.md
I just packaged `presenterm` for [**aur**](https://aur.archlinux.org/). Any arch or based user can install it using aur helpers like yay/paru.
=> feat(install): Arch user repository pkgbuilds // installation guide

README.md, build.rs, flake.lock, flake.nix
Hi,
I'd like to use `presenterm` and I am a Nix&NixOS user.
I've added a simple Nix Flake, based on [Flakebox](https://github.com/rustshop/flakebox).
In a nutshell, once it lands Nix users can very easily run `presenterm` with:
```
nix run github:mfontanini/presenterm -- <args>
```
and also include it in their system configurations etc.
Under the hood it has support for other stuff as well, like cross-compilation:
```
nix build -L .#aarch64-android.release.presenterm
> file result/bin/presenterm
result/bin/presenterm: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, with debug_info, not stripped
```
fancy dev shells, etc. But that's a rabbit hole.
I'm planning to try out `presenterm` in a near future and maybe in the future submit it to `nixpkgs` (an …
=> Add a Nix Flake

README.md, src/builder.rs, src/lib.rs, src/render/layout.rs, src/render/media.rs, src/render/properties.rs, src/render/terminal.rs
This patches the issue brought up in #13. Images can't be rendered on windows (and this will lead to an error running the presentation) but at least the rest of the operations should work.
=> Don't crash if terminal window size can't be found

Cargo.lock, Cargo.toml, README.md, src/builder.rs, src/execute.rs, src/input/source.rs, src/input/user.rs, src/lib.rs, src/markdown/elements.rs, src/markdown/parse.rs, src/presentation.rs, src/presenter.rs, src/render/highlighting.rs, src/render/operator.rs, src/theme.rs, themes/dark.yaml, themes/tokyonight-storm.yaml
This adds code execution for shell blocks (e.g. `bash`, `sh, `shell`, etc) when pressing control+e. For this to work you need to annotate the code block with `+exec` (e.g. `bash +exec`) so that you agree to allow presenterm to run the code. 
I also made this so that you can still change slides as the code is being rendered. Not sure if that's necessary but I think it was simpler to do it this way.
@baduhai would you like to test this and let me know if it works for you? Thanks!
[![asciicast](https://asciinema.org/a/1v3IqCEtU9tqDjVj78Pp7SSe2.svg)](https://asciinema.org/a/1v3IqCEtU9tqDjVj78Pp7SSe2)
Closes #4
=> Add executable blocks

src/builder.rs, src/diff.rs, src/presentation.rs, src/presenter.rs, src/render/draw.rs, src/render/operator.rs
Before this change, a `` would copy the contents of the slide so far, create a new slide, and continue adding content to the current slide. This meant that every pause operation would create a new slide, which has the side effect that the footer's `current_slide` variable changes every time you jump in between a slide's pauses.
With this change a slide is now partitioned into chunks. All slides have at least 1 chunk and every pause creates a new chunk. So this means a slide with 2 pause operations has 3 chunks: what's before the first pause, what's between the first and second, and what's after. This requires dealing with jumps between slides a little different so that you jump through chunks first and then through slides.
Fixes #16
=> Don't create new slide on pauses 

src/builder.rs, src/diff.rs, src/markdown/elements.rs, src/markdown/parse.rs, src/presentation.rs, src/render/draw.rs, src/render/operator.rs
This makes pauses not break the numbering in ordered lists. This is a bit convoluted because from the markdown's perspective, an ordered list with a pause in between is 2 ordered lists. So the logic to realize there was a list before the pause and that we should pick up from the last index is done when constructing the presentation.
This does not work for lists of depth > 0 (e.g. a nested ordered list) because that's not valid markdown. I don't think comrak gives enough information when parsing lists to even get around this so it probably can't be fixed.
Fixes #15
=> Don't reset ordered list number after pause

src/diff.rs, src/presentation.rs, src/presenter.rs
This includes layout operations in the list of operations that are considered to change the content of a slide. This means hot reloading now jumps to a slide if the layout has changed (either column number, column width, or the column itself changes).
Fixes #22
=> Jump to slide if layout changes

src/builder.rs, src/markdown/elements.rs, src/markdown/parse.rs
This includes the real line number when parsing commands fails rather than the bogus "line 1 column 0" you get from `serde_yaml`.
Fixes #26
=> Include real line number on command parse error

src/builder.rs, src/presentation.rs
This makes it so that a list + pause combo doesn't always pop the newline as this only should be the behavior if the thing right after is a list.
Fixes #32.
=> Don't remove newlines after every list + pause

.github/workflows/merge.yaml
This prevents having duplicate jobs.
=> Only run push checks on master

README.md, src/input/source.rs, src/input/user.rs, src/presenter.rs, src/resource.rs
This makes it so that `<C-r>` refreshes the resources, namely images and resources, while in development mode.
Fixes #33.
=> Add keybinding to refresh images and themes

src/builder.rs, src/diff.rs, src/presentation.rs, src/presenter.rs, src/render/engine.rs
This makes it so the template style footer shows up in one-row-to-last rather than in the last one as this looks a little nicer.
Fixes #36
=> Position template style footer one row above bottom

src/builder.rs, src/markdown/elements.rs, src/markdown/parse.rs
comrak doesn't seem to include the front matter's length when setting the source positions so this does it by hand.
=> Offset source positions by hand when input has front matter

src/builder.rs, src/presenter.rs
This fixes the case of list-pause-notlist-list. This needs better tests as it's very fragile!
=> Don't pop new line if list is not right after pause

Cargo.lock, Cargo.toml, README.md, src/builder.rs, src/export.rs, src/lib.rs, src/main.rs, src/markdown/elements.rs, src/markdown/parse.rs
This adds the ability to export presentations to PDF. This needs a separate tool that can be installed via pip.
Fixes #9
=> Allow exporting presentations to PDF

src/builder.rs, src/execute.rs, src/markdown/elements.rs, src/markdown/parse.rs, src/render/highlighting.rs
This allows enabling line numbers on code blocks by using the `+line_numbers` attribute.
=> Allow enabling code block line numbers

src/builder.rs, src/markdown/code.rs, src/markdown/elements.rs, src/markdown/mod.rs, src/markdown/parse.rs
This allows highlighting code block lines by either providing specific lines or line ranges to highlight as part of the code block. e.g. the notation `{1,3,5-7}` highlights lines 1, 3, 5, 6, and 7.
Relates to #41
=> Line highlighting

src/builder.rs, src/diff.rs, src/export.rs, src/main.rs, src/markdown/code.rs, src/markdown/elements.rs, src/markdown/parse.rs, src/presentation.rs, src/presenter.rs
This implements progressive highlighting as an extension to the custom line highlighting implemented in #48. This uses the notation `{1-2|all|1,2,3}` where every group in between `|` is going to be rendered progressively every time you move the slides forward/backwards.
Closes #41
=> Progressive highlighting

src/builder.rs, src/theme.rs
The footer style needs to be an `Option`, otherwise merging themes when overriding causes the original one to be lost.
Fixes #51.
=> Don't override default footer if none is specified

src/render/engine.rs, src/render/media.rs, src/resource.rs
This allows including animated gifs in presentations when using terminals that support the iterm2 protocol (e.g. iterm2 and wezterm).  
Fixes #54
=> Support printing gifs under iterm2

src/render/engine.rs, src/render/terminal.rs
This causes preformatted lines (code blocks and quotes) which are too long and wrap around not to lose the sync we have between the terminal's cursor and where we think it is.
Reported in #54
=> Manually sync terminal row if pre-formatted text wraps

src/render/engine.rs
This makes this #57 a little better.
=> Use max_line_length when word-wrapping pre-formatted blocks

src/export.rs
This otherwise fails if there's no parents.
=> Canonicalize before getting parent

build.rs, src/builder.rs, src/presentation.rs, src/render/terminal.rs, src/style.rs, themes/terminal-dark.yaml, themes/terminal-light.yaml
This adds a `terminal-dark` and `terminal-light` themes that use the terminal's background/foreground colors and uses named terminal colors for elements that need them.
Fixes #64
=> Add terminal colored themes

Cargo.lock, Cargo.toml, src/main.rs, src/render/highlighting.rs
This lets you drop `.tmTheme` files in `~/.config/presenterm/themes/highlighting/` which can then be used to highlight code blocks referencing them by name. 
Fixes #50
=> Allow providing custom syntect themes

src/lib.rs, src/main.rs, src/render/highlighting.rs, src/theme.rs
This allows defining custom themes under `~/.config/presenterm/themes`. These themes can then be used as if they were built in: referencing them by name.
=> Load themes under ~/.config/presenterm/themes

src/builder.rs, src/custom.rs, src/export.rs, src/lib.rs, src/main.rs, src/presenter.rs, src/render/highlighting.rs, src/theme.rs
This adds the ability to drop a yaml file in `~/.config/presenterm/config.yaml` which lets you configure the default theme to be used on presentations. This will override the `--theme` parameter but a presentation configuring the theme via the front matter still has the highest precedence. So `front-matter-theme > dotfile-theme > cli-parameter-theme`.
Example file contents:
```yaml
defaults:
theme: potato
```
=> Allow configuring theme in dotfile

Cargo.lock, Cargo.toml, src/builder.rs, src/export.rs, src/markdown/elements.rs, src/markdown/parse.rs, src/presentation.rs, src/presenter.rs, src/render/media.rs, src/resource.rs, src/typst.rs
This shifts the responsibilities of replacing images during PDF export from presenterm-export to presenterm. This is necessary for latex formulas to be rendered correctly, as those images don't exist in the original markdown file so presenterm-export can't do anything about it. This also simplifies things a bit as presenterm-export doesn't need to hackily half-parse the markdown. 
Needs the presenterm-export changes on https://github.com/mfontanini/presenterm-export/pull/1.
Relates to #6
=> Generate PDF replacement images in presenterm directly

docs/highlighting.md, src/markdown/code.rs, src/markdown/elements.rs, src/render/highlighting.rs
`bat` supports `nix` syntax highlighting.
=> Add syntax highlighting for nix

docs/highlighting.md, src/markdown/code.rs, src/markdown/elements.rs, src/render/highlighting.rs
Saw [this PR](https://github.com/mfontanini/presenterm/pull/78) and realized adding additional languages was easy.
What I want to be able to show is the changes I made to some code, and this is the simplest way to do that.
My editor strips trailing spaces; I can leave them in if you want, though.
=> Add syntax highlighting for diff

src/builder.rs, src/custom.rs, src/export.rs, src/lib.rs, src/main.rs, src/presenter.rs
This allow shaving implicit slide ends by using a setex header (e.g. slide title). This is an optional behavior and can be enabled by editting `~/.config/presenterm/config.yaml` and adding:
```yaml
options:
implicit_slide_ends: true
```
Fixes #65
=> Allow having implicit slide ends

src/export.rs
This makes presenterm forward its own parameters to presenterm-export, which will forward them as-is. This lets us change our own interface in the future (e.g. add more parameters) and have presenterm-export deal with that transparently.
This PR goes along with https://github.com/mfontanini/presenterm-export/pull/3
=> Forward our own parameters to presenterm-export

src/lib.rs, src/main.rs, src/render/engine.rs, src/render/media.rs, src/render/properties.rs, src/render/terminal.rs
This fixes a few things that causes flickering mostly when displaying images:
* We rely on `viuer`'s return value when printing an image to figure out how many rows the cursor moved. This allows us to drop the manual sync that was there and now the terminal never needs to be resynced which is cool.
*  When entering a layout, we were pulling the cursor position from crossterm. This was leftover code from when the `Terminal` type was introduced, and should have (and now does) pulled this information out of that type as it requires no IO.
* Pre-detect `viuer's support for iterm and kitty. Before the latter would be payed when you displayed the first image which could add some flickering. The iterm support was already being loaded but it's done there too for consistency.
cc @rmartine-ias this …
=> Reduce flickering when displaying images

.github/workflows/merge.yaml
This migrates the merge workflow to use dtolnay/rust-toolchain as actions-rs is deprecated. The release one still uses the other one but it should be migrated as well.
=> Migate merge workflow to dtolnay/rust-toolchain

scripts/test-pdf-generation.sh, src/export.rs
It seems like `viuer` thinks that we support the iterm image protocol when exporting a pdf. Unset the `LC_TERMINAL` environment variable so it doesn't believe that anymore and it emits images as ascii blocs.
Fixes #98
=> Unset LC_TERMINAL before exporting to pdf

scripts/test-pdf-generation.sh, src/export.rs, src/presenter.rs, src/render/draw.rs, src/render/engine.rs, src/render/media.rs
This disables kitty/iterm2 when running in export mode. This otherwise can get messed up when running under some terminals, e.g. iterm, and we don't want to leave it up to chance: we know we want ascii blocks in export mode.
Fixes #98
=> Don't enable kitty/iterm in export mode

src/builder.rs, src/custom.rs, src/presentation.rs, src/theme.rs
Now any unknown field name in the front matter, presentation or config file will cause an error. This should prevent (honest) user errors like the one in #96.
=> Deny unknown fields in yaml models

docs/config.md, src/custom.rs
Ideally we'd also do these validations on theme files but apparently serde and deny_unknown_fields don't get along well with our flattened fields so maybe we'll do that some other day.
Fixes #104
=> Validate config file and fix docs

src/builder.rs, src/custom.rs, src/main.rs
This allows setting a new [config option](https://github.com/mfontanini/presenterm/blob/master/docs/config.md) which makes the behavior in #106 enabled for the entire presentation. e.g. add in front matter
```markdown
---
options:
incremental_lists: true
---
```
And now all lists will have an implicit pause in between. Do note that if you add an explicit `` in between bullet points, there will be double pauses but that's up to you.
Relates to #105
=> Allow using incremental lists globally

src/markdown/text.rs
Found via `typos --hidden --format brief`
=> Fix typo, peice -> piece

src/export.rs, src/main.rs
This propagates the `--theme` parameter down to the exporter when exporting PDFs so that the theme you manually specify is respected in the output file.
=> Propagate --theme down to exporter

src/presenter.rs
For some reason I thought the first load should error different than if you load a well formed presentation and then modify it, causing a reload that detects the error and displays it. Upon playing around with presentations this becomes very annoying as errors behave inconsistently.
This treats that first error as the same as any other.
=> Display first presentation load error as any other

src/input/user.rs
crossterm on Windows seems to emit key release events. These should be ignored as otherwise a single key press will be seen as two.
Fixes #114
=> Ignore key release events

themes/dark.yaml, themes/light.yaml, themes/tokyonight-storm.yaml
The foreground color for execution in built-in themes wasn't being set so it could look bad depending on the environment.
Fixes #121
=> Explicitly set execution output fg color in built-in themes

src/custom.rs, src/lib.rs, src/main.rs, src/presenter.rs, src/render/draw.rs, src/render/engine.rs, src/render/layout.rs, src/render/media.rs, src/render/properties.rs, src/render/terminal.rs
This PR attempts to add _some_ support for images on Windows. Specifically:
* Getting the terminal size in pixels fails in that platform so instead we default to a 16 pixel font size and let you specify some other via the config file. This ain't great but it gets the job done.
* WezTerm seems to completely break if you hide the cursor and then display images on Windows (works fine in Linux!). So in that specific combo we don't hide the cursor. This is done only in that scenario as not hiding the cursor is suboptimal as you can sometimes see it moving, especially when printing images. Unfortunately without this images are completely broken there so this is better than nothing.
There's still more work to be done here. e.g. this doesn't work well in the git bash for windows terminal …
=> Support images to some extent on Windows

.github/workflows/release.yml
While trying newly created manifest for scoop (ScoopInstaller/Main#5409), noticed that hash files are absent for both generated Windows artifacts.
Suppose it could be useful to fix this injustice since generated hashes are already available for all the other artifacts.
Tested [here](https://github.com/aliesbelik/presenterm/actions/runs/7470080963/job/20328289340), sample release [here](https://github.com/aliesbelik/presenterm/releases/tag/v0.4.2).
=> Add hashes for windows artifacts

examples/demo.md, src/builder.rs, src/diff.rs, src/input/source.rs, src/input/user.rs, src/markdown/text.rs, src/presentation.rs, src/presenter.rs, src/render/draw.rs, src/render/engine.rs
This adds a slide index modal, which shows the slide number + slide name for all the slides (capped if there's too many). You can still move forward/backward and jump to slides using the usual keybindings while having this modal open, so you can use this to navigate and find a particular slide you may be looking for.
This is how this looks like:
[![asciicast](https://asciinema.org/a/1VgRxVIEyLrMmq6OZ3oKx4PGi.svg)](https://asciinema.org/a/1VgRxVIEyLrMmq6OZ3oKx4PGi)
Fixes #123
=> Add slide index modal

src/custom.rs, src/input/source.rs, src/input/user.rs, src/main.rs, src/presentation.rs, src/presenter.rs
This allows defining custom keybindings in the config file under `~/.config/presenterm/config.yaml`. I will document this along with the next release but you can do things like:
```yaml
bindings:
next_slide: ["l", "<right>"]
previous_slide: ["h", "<left>"]
first_slide: ["1"]
go_to_slide: [":<number><cr>"]
```
By default all mappings are the same as before, but they can be overridden one by one.
This for now performs only some checks on conflicting keybindings but it won't detect things like "potato" vs "ta" in its current form.
=> Allow defining custom keybindings in config file

src/custom.rs, src/input/source.rs, src/input/user.rs, src/presenter.rs
This allows closing the open modal (currently only the slide index) using escape, but can be configured to use some other binding.
Fixes #129
=> Allow closing modal using escape

src/render/media.rs
This ensures if your terminal uses sixel, the PDF export won't fallback to it and potentially break.
=> Detect sixel early and fallback to ascii blocks properly

src/lib.rs, src/main.rs, src/presenter.rs, src/render/media.rs
This lets you specify the preferred image protocol. Note that if that protocol isn't supported, this will fall back to ascii blocks so it's just a hint that's useful in terminal emulators that support more than one mode.
=> Allow specifying the preferred image protocol

src/custom.rs, src/main.rs, src/processing/builder.rs
This allows using the `options.end_slide_shorthand` key in the front matter and/or config file under `~/.config/presenterm/config.yaml` to turn thematic breaks (`---`) into the delimiter between slides. The original `` notation can still be used when this is enabled, this only allows opting into this extra behavior.
Fixes #137
=> Allow using thematic breaks to end slides

src/markdown/text.rs, src/processing/builder.rs, src/processing/modals.rs, src/style.rs, src/theme.rs, themes/dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
The colors for modals (currently only the slide index) can now be configured via `modals.colors`. Also, the selected line in the slide index modal can be configured via `modals.selection_colors`. 
Fixes #130
=> Allow configuring modals styles

src/markdown/elements.rs, src/markdown/parse.rs, src/markdown/text.rs, src/presentation.rs, src/processing/builder.rs, src/processing/footer.rs, src/processing/modals.rs, src/render/draw.rs, src/render/engine.rs, src/render/text.rs
This PR:
* Renames the text related types to have more sensible names. 
* Changes the `WeightedTextBlock` (former `WeightedLine`) so that when it's constructed from text chunks it collapses consecutive text chunks that use the same style into the same block. This helped reduce memory usage slightly and should make the rendering slightly faster as there's fewer blocks to be traversed.
=> Refactor text types

src/custom.rs, src/export.rs, src/input/source.rs, src/input/user.rs, src/main.rs, src/presentation.rs, src/presenter.rs, src/processing/builder.rs, src/processing/modals.rs, src/render/draw.rs
This adds a modal, bound to `?` by default, that displays a list of all key bindings.
=> Add key bindings modal

src/custom.rs, src/export.rs, src/input/source.rs, src/input/user.rs, src/presentation.rs, src/presenter.rs, src/processing/modals.rs
This allows potentially adding a real "next slide" in the future that skips chunks and mutations and jumps to the true next slide.
=> Rename next/previous slide bindings to next/previous

src/render/engine.rs, src/render/terminal.rs
This reduces flickering when printing images.
=> Use synchronized updates to remove flickering

src/diff.rs, src/export.rs, src/lib.rs, src/main.rs, src/media/kitty.rs, src/media/mod.rs, src/media/printer.rs, src/media/register.rs, src/presentation.rs, src/presenter.rs, src/processing/builder.rs, src/processing/modals.rs, src/render/engine.rs, src/render/terminal.rs, src/resource.rs, src/typst.rs
This creates a background image for every modal when using kitty. This is necessary as kitty does not use a "last write wins" policy when writing images over text, so without this the modals show up behind images in slides.
Fixes #153
=> Print an image as background for modals when using kitty

Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs, src/media/emulator.rs, src/media/kitty.rs, src/media/mod.rs
This PR:
* Detects the terminal emulator we're using.
* Figures out which image protocol to use.
* Turns the `--image-protocol` cli arg from a hint into a respected value, at least for the kitty and iterm protocols.
The main motivation for this is that `viuer` has limited detection, e.g. it doesn't know wezterm supports the kitty protocol so now, while it still uses the iterm one by default, you can pass in `--image-protocol kitty-local` when using wezterm and it will be respected. This is also some ground work to be able to work on #72 next.
=> Detect image protocol instead of relying on viuer

src/main.rs, src/media/emulator.rs, src/media/graphics.rs, src/media/kitty.rs, src/media/printer.rs, src/media/scale.rs, src/processing/builder.rs
This uses the [unicode placeholder strategy](https://sw.kovidgoyal.net/kitty/graphics-protocol/#unicode-placeholders) under kitty to get images (including gifs) to work when running under tmux. Caveats:
* Gifs only seem to really work correctly under tmux 3.3a. 3.2a sometimes doesn't display them upon the first try.
* This doesn't currently detect kitty (or wezterm) correctly when running in tmux so if you're using tmux on either of those terminals that support the kitty protocol, you need to pass `--image-protocol kitty-local` (`kitty-remote` seems to not work great). I may add some better detection but at least this currently works.
* I tried to get this to work under the [iterm protocol](https://iterm2.com/documentation-images.html) as well but I'm afraid it won't work. tmux has some …
=> Use unicode placeholders to print images under kitty+tmux

src/processing/builder.rs
This adds a `new_lines` (`newlines` also works) and a `new_line` (`newline` also works) command that lets you add line breaks explicitly in a slide. e.g.
```markdown
hi
mom
hi
```
Will add an extra 10 new lines in between the first 2 lines of text, and an extra one in between the second and third.
=> Add newlines command

src/main.rs
This breaks the output json otherwise.
=> Don't preload graphics mode when generating pdf metadata

Cargo.lock, Cargo.toml, src/custom.rs, src/export.rs, src/main.rs, src/media/ascii.rs, src/media/emulator.rs, src/media/graphics.rs, src/media/mod.rs, src/media/printer.rs, src/media/sixel.rs, src/presenter.rs, src/render/draw.rs, src/render/engine.rs, src/render/properties.rs
This stops using viuer to render images using sixel and instead does something very similar but within this codebase. The reason for this is when testing sixel support in wezterm I would get tiny images, which is because the font size is hardcoded in viuer. Here instead we pull it from the config file so you can configure it to be whatever works for your environment.
This also allows forcing the use of sixel. Because viuer **always** checks if a mode is supported before using it, there's no way to override that decision and say "use sixel!". With this change, if you pass in `--image-protocol sixel` it will use it (which means if you don't support it it will break).
=> Improve sixel support

src/custom.rs, src/lib.rs, src/main.rs, src/media/emulator.rs
This lets you use the `defaults.image_protocol` config to set the preferred image protocol. The cli argument still takes precedence over this.
=> Allow setting image protocol in config file

src/media/iterm.rs
We're already ensuring the aspect ratio is preserved manually so there's no need for this.
=> Don't preserve aspect ratio in iterm protocol

Cargo.lock, Cargo.toml, src/main.rs
The config file is now on:
* `~/.config/presenterm/config.yaml` on linux (this is unchanged).
* `~/Library/Application Support/presenterm/config.yaml` in macOS.
* `~/AppData/Roaming/presenterm/config/config.yaml` in windows.
Fixes #180
=> Use `directories` to find config directory path

Cargo.lock, Cargo.toml, src/export.rs, src/media/ascii.rs, src/media/printer.rs, src/presentation.rs, src/processing/builder.rs, src/processing/modals.rs, src/render/engine.rs
This removes the `viuer` dependency, which at this point was only being used for ascii-blocks graphics, and replaces it with a hand rolled version. Along with this change, this respects transparency better, as in, rather than printing a chess board pattern where `rgba(0, 0, 0, 0)` pixels show up, it instead uses the theme's background.
This also fixes a problem that viuer seems to have where it sometimes adds an extra line at the bottom in ascii mode.
On the left is the new version, on the right the old one using viuer:
=> Stop using viuer for ascii blocks graphics mode

src/input/user.rs
This was breaking stateful input actions such as `<number>G` on windows.
=> Don't clear input state on key release event

src/custom.rs, src/main.rs, src/presentation.rs, src/processing/builder.rs
This allows setting the `strict_front_matter_parsing` option to false in the config file, which in turn allows unknown fields in the front matter. The solution is kind of crappy as I can't keep this optional without keeping the nice error message in the strict case (e.g. expected one of a, b, c).
Fixes #189
=> Allow making front matter strict parsing optional

src/main.rs, src/markdown/parse.rs
The content of block quotes is turned back into commonmark via comrak, but it seems as part of that symbols that have a meaning in markdown (e.g. `!` or `[`) are escaped. This fixes that by unescaping them back into their original form.
Fixes #194
=> Unescape escaped symbols in block quotes

src/main.rs
`ProjectDirs::from_path` is discouraged and it seems it wasn't respecting XDG_CONFIG_HOME. Besides this, it seems that `directories` only respects the XDG spec in linux so this makes it respect it in all platforms.
Fixes #192
=> Respect XDG_CONFIG_HOME env var

docs/src/guides/themes.md, themes/catppuccin-mocha.yaml
This adds a new default color theme based on the [catppuccin-mocha](https://github.com/catppuccin/catppuccin) color palette.
=> Add catppuccin-mocha theme

docs/src/guides/installation.md
Now that ScoopInstaller/Main#5409 is merged, we can add Scoop to the list of package managers.
=> docs: add Scoop to package managers

src/processing/builder.rs, src/style.rs, src/theme.rs, themes/catppuccin-mocha.yaml, themes/dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
This allows configuring slide titles by using the `bold`, `italics`, and `underlined` properties under `slide_title` in the theme definition. Before this change, slide titles were always bold, whereas now they are non-bold by default, but built-in themes all set `slide_titled.bold` to `true` so the behavior is preserved for those. This means any custom themes will no longer have bold slide titles unless they do the same.
=> Allow customizing slide title style

build.rs
Sort input file list
so that `themes.rs` builds in a reproducible way
in spite of non-deterministic filesystem readdir order.
See https://reproducible-builds.org/ for why this is good.
Without this patch, `themes.rs` and the resulting `presenterm` binary would differ thusly:
```diff
-  theme_name: base16-eighties.dark
+  theme_name: GitHub
```
This patch was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
=> Sort input file list

themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml
Closes [#203](https://github.com/mfontanini/presenterm/issues/203)
This adds the remaining [catppuccin](https://github.com/catppuccin/catppuccin) color schemes as default themes.
Hope you don't mind I stole your thunder @sp3ctum !
=> Add frappe, latte and macchiato catppuccin themes

build.rs, src/demo.rs, src/export.rs, src/input/user.rs, src/lib.rs, src/main.rs, src/presenter.rs, src/processing/builder.rs, src/theme.rs, themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml
This adds a `--list-themes` parameter that showcases a single demo slide on all available themes. This includes built-in as well as your own ones under `$CONFIG/themes/`:
[![asciicast](https://asciinema.org/a/zeV1QloyrLkfBp6rNltvX7Lle.svg)](https://asciinema.org/a/zeV1QloyrLkfBp6rNltvX7Lle)
=> Add parameter to list themes

src/demo.rs, src/main.rs, src/media/printer.rs, src/presentation.rs, src/presenter.rs, src/processing/builder.rs, src/processing/code.rs, src/processing/execution.rs, src/render/draw.rs, src/render/engine.rs, src/render/mod.rs, src/render/terminal.rs, src/render/text.rs, src/render/validate.rs
This adds a `--validate-overflows` which, upon loading the presentation or resizing the terminal screen, will run checks to ensure the presentation doesn't:
* Overflow the screen vertically/horizontally. This can happen when you use block quotes or code blocks.
* Overflow a column layout rect. That is, if you use block quotes or code blocks within a column, it can happen that the column is small enough and can't fit its content.
Relates to #61
[![asciicast](https://asciinema.org/a/RguCyLDTDJIzK3lNT4VN3mgID.svg)](https://asciinema.org/a/RguCyLDTDJIzK3lNT4VN3mgID)
=> Allow validating whether presentation overflows terminal

src/custom.rs, src/lib.rs, src/main.rs
This allows configuring the overflow validation mode introduced in #209 in the config file via `defaults.validate_overflows`:
* `always` to always validate.
* `never` to never validate (this is the default).
* `when_presenting` to validate when running in presentation mode (`-p`).
* `when_developing` to validate when running in development mode (the default mode).
=> Allow setting validate overflows mode in config file

src/processing/builder.rs, src/processing/code.rs, src/render/highlighting.rs, src/theme.rs
This allows setting the theme key `code.background` (defaults to `true`) which controls whether code blocks have a background color. Note that the background color comes from the code highlighting theme being used, this only controls whether that background is visible or not.
Enabling this (the default):
Disabling this:
=> Allow having code blocks without background

src/render/highlighting.rs, src/theme.rs
Allow re-enabling a disabled `code.background` (follow up on #215).
=> Allow overriding `code.background`

README.md, docs/src/introduction.md, examples/README.md, examples/code.md, examples/footer.md
This adds 2 more example presentations, showcasing more code blocks and footer styles.
=> Add more example presentations

src/processing/builder.rs, src/theme.rs, themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml, themes/catppuccin-mocha.yaml, themes/dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
This allows configuring the `block_quote.colors.prefix` attribute to configure the color of the block quote prefix (which defaults to a vertical line). If this key is absent, the color will be the same as the `block_quote.colors.foreground` one.
Along with this change I changed all the built in themes to have a prefix of the same color as the slide title except for a couple of light themes where I had to pick a different one.
=> Add color to prefix in block quote

src/tools.rs
This now prints a message like the following when a tool (e.g. `presenterm-export`) is missing:
```
spawning 'presenterm-export' failed (is 'presenterm-export' installed?)
```
Relates to #220
=> Suggest a tool is missing when spawning returns ENOTFOUND

docs/src/guides/code-highlight.md, src/markdown/code.rs, src/markdown/elements.rs, src/render/highlighting.rs
Hi, I've really been enjoying using `presenterm`, thanks to the owners/maintainers of this project for putting in so much hard work! 
Just really needed `ruby` code support so I thought I'd add it. Please feel free to let me know if any further changes are required, I just based my changes off of #82.
=> Add Support for Ruby Code Highlighting

CHANGELOG.md
Previously in contained the number of the issue but it was not a link.
Created the edits with this beautiful regex 😄 
- `%s,\#\(\d\+\),[#\1](https://github.com/mfontanini/presenterm/issues/\1),g`
=> docs: CHANGELOG.md contains clickable links to issues

config.sample.yaml
Hi, noticed this setting is missing from the default config.
I'm not sure if you'd like to include all keys there by default. In case it's not necessary, this change can be discarded 🙂
=> chore(config): include strict_front_matter_parsing in default config

src/input/user.rs, src/presentation.rs, src/processing/builder.rs, src/render/highlighting.rs, src/theme.rs
The warnings became visible in rust-analyzer. I could also see the warnings on the command line by executing
`cargo clippy --all-targets`
I fixed all the warnings using rust-analyzer's LSP code actions.
The full list of warnings:
<details><summary>Details</summary>
<p>
```rust
Checking presenterm v0.7.0 (/Users/mikavilpas/git/presenterm)
warning: this expression creates a reference which is immediately dereferenced by the compiler
--> src/input/user.rs:535:43
|
535 |         let result = binding.match_events(&events);
|                                           ^^^^^^^ help: change this to: `events`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
= note: `#[warn(clippy::needless_borrow)]` on by default
warning: explicit …
```
=> refactor: fix all clippy warnings

Cargo.lock, Cargo.toml, config.sample.yaml, schema.json, src/custom.rs, src/input/user.rs, src/main.rs
This change introduces a JSON schema for the configuration file. This schema is used to validate the configuration file and provide feedback to the user if the configuration file is invalid.
https://github.com/mfontanini/presenterm/assets/300791/9b9e7c45-6f2f-4a45-9806-60a8413c2185
To use this schema, the schema must be referenced in the yaml configuration file like this:
```yaml
```
> See the documentation for this feature here: https://github.com/redhat-developer/yaml-language-server?tab=readme-ov-file#using-inlined-schema
This configures the [yaml-language-server](https://github.com/redhat-developer/yaml-language-server) to use the schema.json file to validate the configuration file. The language server is well supported in editors such as
- Neovim with …
=> feat(config): add JSON schema for validation,completion,documentation

src/main.rs, src/typst.rs
This allows using images in typst by passing in the `--root` parameter to specify the root path. All images must have an absolute path starting from the directory where the presentation is. So e.g. if you have a layout like
```
foo/presentation.md
foo/image1.png
```
In order to use `image1.png` inside typst in that `presentation.md` file you need to:
~~~markdown
```typst +render
#image("/image1.png")
```
~~~
Fixes #233
=> Allow using image paths in typst

src/media/kitty.rs, src/processing/builder.rs, src/theme.rs
This allows:
* Skipping the footer in the intro slide by setting the theme's `intro_slide.footer` property to `false`.
* Skipping the footer in any slide by using a command ``.
Fixes #238
=> Allow explicitly disabling footer in certain slides

config-file-schema.json, config.sample.yaml, src/custom.rs, src/input/source.rs, src/input/user.rs, src/presentation.rs, src/presenter.rs, src/processing/modals.rs
This introduces 2 new keybindings: `next_fast` and `previous_fast`. These behave like `next`/`fast` except they don't go through intermediate pause states in a slide and instead just jump between no pauses shown and all pauses shown in a slide.
Fixes #241
=> feat: allow jumping fast between slides

src/processing/execution.rs
This transforms tabs into spaces so we can highlight them properly. This defaults to 4 tabs per space but if someone complains we can make it configurable.
Fixes #240
=> fix: display background color behind '\t' in code exec output

.github/workflows/merge.yaml
The nix flake build step is getting stuck for 50 minutes on the nix cache. This removes the cache altogether as it seems like it's slowing build times rather than improving them.
=> chore: remove nix cache in CI

README.md, docs/src/guides/installation.md
`presenterm` is now packaged in the official repositories: <https://archlinux.org/packages/extra/x86_64/presenterm/> 🥳
=> docs: Update install instructions for Arch Linux

src/execute.rs
Fixes https://github.com/mfontanini/presenterm/issues/247.
This PR ensures we wait for the code execution process to completely exit, when determining its exit status. This way, we do not erroneously show the `[finished with error]` output when the process had not exited yet.
=> fix(code-exec): wait for code execution process to exit completely

Cargo.lock, Cargo.toml, examples/code.md, src/execute.rs
Closes https://github.com/mfontanini/presenterm/issues/251.
This uses the [os_pipe](https://crates.io/crates/os_pipe) crate to capture both `stdout` and `stderr` from code execution, displaying them interleaved as you would see it in the terminal. The interactivity of seeing each output line as it happens (instead of all at the end) is retained.
https://github.com/dmackdev/presenterm/assets/79006698/0b93e4b3-96dd-4e98-9ac0-e03dd1b43514
=> feat: show `stderr` output from code execution

executors/Kotlin.sh
Adds `Kotlin.sh` to execute Kotlin scripts - see https://kotlinlang.org/docs/command-line.html#run-scripts.
Using Kotlin scripts instead of compiling to a `jar` first and then running it with `java` means that the `main` function boilerplate does not need to be included in the snippet.
=> feat: add kotlin script executor

src/markdown/elements.rs, src/processing/builder.rs, src/processing/execution.rs, src/processing/separator.rs, src/theme.rs, themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml, themes/catppuccin-mocha.yaml, themes/dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
This changes the error reporting when the execution of a code snippet fails so that instead of appending a "[finished with error]" string at the end, we display "finished with error" at the little status box in between the code snippet and the execution output. See screenshot for reference. @dmackdev thoughts on this? I found the current UI kind of annoying when running broken code snippets. Maybe as an addition to this, the "finished with error" could have a red (configurable) color so it's more obvious.
=> feat: use a cleaner execution error UI

src/processing/execution.rs
=> fix: use unicode width to calculate execution output's line len

src/main.rs, src/processing/builder.rs, src/theme.rs
This allows custom themes to have an `extends` key that should include another theme (built in or custom) name which indicates this theme should inherit that one. Any properties not set by this theme will be inherited from the theme you extend from. This is also recursive so you can have one theme extending from a theme that extends another.
Fixes #262
=> feat: allow custom themes to extend others

src/third_party.rs
The mermaid snippet rendering introduced in #268 works but the mermaid cli is **very slow** so every modification to the presentation while developing is painfully slow. This adds caching at the third party image render layer. Images already live forever, this just uses a hashmap from the input string -> the image itself. We could also hash the inputs but that adds another dependency and inputs should be small enough that this would be negligible.
cc @mikavilpas
=> feat: cache third party rendered images

executors/nushell.sh, src/markdown/elements.rs, src/render/highlighting.rs
This adds nushell code execution. Code highlighting is not supported yet as `bat` doesn't support it, so nushell snippets won't have any highlighting but can be executed.
Relates to #271
=> feat: add nushell code execution

config-file-schema.json, src/custom.rs, src/main.rs, src/processing/builder.rs
This changes the code snippet execution so that it is disabled by default and users need to opt in by either:
* Running presenterm with the `-x` flag.
* Set the `snippet.exec.enable` property to true in their config files.
This aims to make running untrusted presentations more secure. You can always set the property in your config file if you only ever run your own presentations, but by default this prevents opening a presentation someone else wrote and accidentally executing code in one of the slides that does something malicious.
=> feat!: force users to explicitly enable code execution

config-file-schema.json, src/custom.rs, src/main.rs, src/third_party.rs
The `snippet.render.threads` config key now allows configuring how many threads you want to have. The default is 2.
=> feat: allow configuring snippet rendering threads

src/presentation.rs, src/presenter.rs, src/processing/execution.rs, src/third_party.rs
This changes the logic that processes the async rendered blocks (code execution output and typst/mermaid/latex `+render` snippets) to avoid re-rendering. Before this was okay as it only affected code execution but now that conversion to images also happens asynchronously this can cause some unnecessary flickering.
=> feat: avoid re-rendering code output and auto rendered blocks

src/diff.rs, src/execute.rs, src/presentation.rs, src/processing/builder.rs, src/processing/code.rs, src/processing/execution.rs, src/processing/separator.rs, src/render/engine.rs
This shrinks the snippet execution output so it tries to fit the code snippet size. Without this change the execution output would always fit the width of the entire screen/layout which looked a bit weird if output lines were too short.
=> feat: shrink snippet execution output to match code block width

src/processing/builder.rs, src/processing/code.rs
This applies the same style as code snippet line numbers to non highlighted code lines as they otherwise still stand out quite a bit.
Fixes #285
=> feat: dim non-highlighted code snippet lines

config-file-schema.json, src/custom.rs, src/diff.rs, src/main.rs, src/markdown/elements.rs, src/markdown/parse.rs, src/media/scale.rs, src/presentation.rs, src/processing/builder.rs, src/render/engine.rs
This adds support for scaling images. Images can, for now, only be scaled to a percentage of the screen width wise. To do this, use the notation `![image:width:50%](image-path)` (shorthands are also `image:width:50` or `image:w:50`). The reason for having a prefix is I've seen some people wanting to be able to pull presentations made with other tools so I don't want to make any assumptions about what those presentations have inside image tags.
@mikavilpas could you give this a shot and lmk your thoughts? I still need to add some stuff and polish this but it's functional already.
Fixes #260
=> feat: allow scaling images

src/markdown/code.rs, src/markdown/elements.rs, src/processing/builder.rs
The '%' wasn't initially made required but I think in the long run this is a bad idea. This makes it required.
=> feat: make percent required in width attribute

src/tools.rs
The mermaid CLI seems to somehow sometimes consume something from (the inherited) stdin which causes raw mode to break in presenterm. This closes stdin by default, which fixes this issue and also seems like a sane default.
=> fix: close child process stdin by default

src/processing/builder.rs
This error message was far from descriptive.
=> fix: add more descriptive error message when loading image fails

src/processing/builder.rs
The transparency in the modal background sounds nice but it looks bad depending on whether there's an image behind it and the color it uses. This disables the transparency so it always looks good regardless of what's behind it.
=> fix: don't use transparency in kitty modal background

src/render/draw.rs
All error messages are no aligned to left, with enough padding to center them a bit. This otherwise looks off.
=> fix: align all error messages to left

executors.yaml, src/execute.rs
Running compiled language snippets wasn't working on windows because the "current dir" parameter to `Command` behaves differently in each platform.
=> fix: allow executing compiled snippets in windows

src/export.rs, src/main.rs, src/presenter.rs, src/tools.rs
If mermaid wasn't installed and you ran a pdf export, it would generate a pdf with just the failure error over and over again. This PR causes presenterm to fail instead.
=> fix: exit with error on async render error in export mode

src/export.rs, src/third_party.rs
A recent change caused async render blocks (mermaid, typst) to change the following lines' background color.
=> fix: reset colors properly after async blocks in export mode

docs/src/guides/mermaid.md, docs/src/guides/themes.md, src/theme.rs, src/third_party.rs, themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml, themes/catppuccin-mocha.yaml, themes/dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
Hello!
Changes:
- add mermaid theme docs
- change default mermaid bg to `transparent` (this seems to be how Github renders mermaid charts)
- add sensible mermaid default based on theme
I noticed that the `mermaid` theme parameters didn't make it into the documentation so I decided to add it.
I also tried to add sensible mermaid theme defaults to better match the supported themes instead of always having to override the theme. For instance, on the `dark` theme the original mermaid defaults (bg: white, theme: default) are quite jarring:
But updating to (bg: transparent, theme: dark) looks much nicer:
Thanks!
=> feat: add mermaid docs and sensible defaults

Cargo.lock, Cargo.toml, src/ansi.rs, src/lib.rs, src/markdown/text.rs, src/processing/execution.rs, src/render/engine.rs, src/render/text.rs, src/style.rs
This processes execution output's ansi escape codes and turns them into `WeightedTexBlock`. This can then be rendered so that we:
* Get colored output automatically.
* Handle lines that are too long to fit on the screen automatically.
This needs more testing, I just tested a couple of commands and it works fine but I didn't thoroughly test yet.
This is based on the initial work done on #296.
cc @DrunkenToast @calebdw I would appreciate if you could give this PR a test. It's only handling a very tiny subset of escape codes so I wouldn't be surprised if something failed. At least I tried basic things like `ls --color=always` and piping stuff to `lolcat` and they both seem to work fine to me.
=> feat: process colored output from execution output

src/presentation.rs, src/processing/builder.rs, src/theme.rs, themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml, themes/catppuccin-mocha.yaml, themes/dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
Hello!
Closes #312 
This PR adds fields for the presentation `event`, `location`, and `date`---these are optional fields but are common frontmatter elements, particularly if the presentation is for a larger conference / event.
Example:
~~~markdown
---
title: How to Think Like a Designer
sub_title: It's easier than you think
event: Laracon US 2024
location: Dallas, TX
date: 2024-08-28
author: Jack McDade
---
~~~
Thanks!
P.S., I'm really new to Rust so sorry if I didn't do thing in the idiomatic Rust way!
=> feat: add event, location, and date frontmatter

config.sample.yaml, docs/src/guides/configuration.md, src/custom.rs
Hello!
This PR adds `q` to the list of exit commands---`q` is a common key used by many programs to exit such as:
- less
- man pages
- vim/neovim
- top/htop/btop
- lookatme
- lazygit
- etc.
This allows both `<c-c>` (the SIGINT signal) and `q` (the common exit key) to exit `presenterm`.
Thanks!
=> feat: allow closing with `q`

src/ansi.rs, src/diff.rs, src/markdown/parse.rs, src/markdown/text.rs, src/presentation.rs, src/processing/builder.rs, src/processing/code.rs, src/processing/execution.rs, src/processing/footer.rs, src/processing/modals.rs, src/processing/separator.rs, src/render/engine.rs, src/render/highlighting.rs, src/render/terminal.rs, src/render/text.rs, src/style.rs, src/third_party.rs
This makes it so that code blocks don't overflow to the right of the code block but instead how you'd expect them to: by creating a new line within the code block rect, properly colored and stuff.
Fixes #289
cc @DrunkenToast can you give this a shot? It seems to work well including line counts and all.
=> feat: handle code overflow

src/tools.rs
I am not sure if Windows platform support is of any importance but I encountered an issue where `mmdc` cannot be found on Windows. This is due to this [issue](https://doc.rust-lang.org/std/process/struct.Command.html#implementations) where `Command::new()` on Windows works in this way: "if the file has a different extension, a filename including the extension needs to be provided, otherwise the file won’t be found.". 
Since mmdc on Windows is an alias for the `mmdc.cmd` script and not an `exe`, this updates the name used to find the mmdc tool.
=> fix: support mmdc on windows

src/diff.rs, src/export.rs, src/presentation.rs, src/processing/code.rs, src/processing/execution.rs, src/processing/footer.rs, src/processing/modals.rs, src/processing/separator.rs, src/third_party.rs
Now diffing to figure out if something dynamic changed is always handled by `Differ` so this can have a default impl.
=> chore: add default `diffable_content`

src/processing/execution.rs, src/theme.rs, themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml, themes/catppuccin-mocha.yaml, themes/dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
This makes it so that executable snippets always have the status bar shown, which serves as an indication that a code snippet is executable.
Fixes #278
=> feat: always show snippet execution bar

config-file-schema.json, src/custom.rs, src/execute.rs, src/main.rs, src/processing/builder.rs, src/processing/code.rs, src/processing/execution.rs
This adds the `+exec_replace` attribute that is basically an `+exec` except the output of the snippet's execution replaces the snippet itself. This allows using tools that emit ascii art, colorize outputs, etc.
I added a new set of configs to enable this (`-X` as a cli parameter and `snippet.exec_replace.enable` in the config file) as this adds a whole other level of danger when running someone else's presentation so I don't think the configs for `exec` are enough to protect users.
Fixes #292
=> feat: allow snippets to be executed and replaced with output

config-file-schema.json, executors.yaml, src/custom.rs, src/execute.rs, src/processing/builder.rs, src/processing/code.rs
This moves the hidden line prefix into the executors file. This allows making this more explicit and harder to miss, and also allows custom executors in config files to define this without having to touch the code.
Fixes #313
=> feat: move hidden line prefix into executors file

src/processing/builder.rs, src/processing/footer.rs
Hello!
This PR adds some more variables that can be used in the footer template (basically everything available in the slide metadata):
- `{title}`
- `{sub_title}`
- `{location}`
- `{event}`
- `{date}`
There may be a better way of including all the metadata in the FooterContext without having to repeat all the definitions?
I tried to add a default footer template, but I couldn't seem to decouple the footer template itself from the `template` style.
The following template is very common in presentations and I think it would make a great default:
```yaml
left: "{author}"
center: "{title}" # this can also be a short title
right: "{current_slide} / {total_slides}"
```
Ideally, I would like to just be able to set the style to `template` and have the default template used:
```yaml
theme: …
```
=> feat: add template variables

src/processing/padding.rs
=> fix: don't crash on code block with only hidden-line-prefixed lines

src/markdown/elements.rs, src/markdown/parse.rs, src/processing/builder.rs
This adds proper styling (bold, italics, etc) to block quotes.
Fixes #341
=> feat: style markdown inside block quotes properly

src/diff.rs, src/presentation.rs, src/processing/builder.rs, src/processing/code.rs, src/processing/execution.rs, src/processing/separator.rs, src/render/engine.rs, src/render/text.rs
This fixes a styling issue leftover from #320 where there was no padding being applied to the right of wrapped code block lines.
=> fix: add padding to right of code block wrapped lines

src/processing/code.rs
This replaces `\t` in code snippets with 4 spaces. If you'd prefer a number of spaces different than 4 please stop using this cursed character.
Fixes #355
=> fix: translate tabs in snippet to 4 spaces

src/theme.rs, themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml, themes/catppuccin-mocha.yaml, themes/dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
This makes the footer in built in themes be a template with `{current_slide} / {total_slides}` in the right. The progress bar was "cool" but it's not very professional so I don't think it should be the default.
Relates to #339 #357
=> feat!: use "template" footer in built-in themes

src/processing/builder.rs, src/processing/code.rs, src/processing/execution.rs, src/theme.rs
This adds a `+no_margin` attribute to code blocks which removes extra margins. For themes that specify a vertical/horizontal padding (like all built in themes), the padding is still present even when using this. This only removes the margin that typically extends a bit right if your code snippet's max line length is too short.
This is especially useful when using `+exec_replace`  so you don't get any extra margin and instead get the executed program's output as-is. For example, the following now looks like this:
~~~markdown
```bash +exec_replace +no_margin
echo "hello world" | qrencode -t utf8
```
~~~
Fixes #349
=> feat: add `+no_margin` to remove margin in code blocks

src/execute.rs, src/processing/builder.rs, src/processing/code.rs, src/processing/execution.rs, src/render/terminal.rs
This introduces a new `+acquire_terminal` snippet attribute which causes the snippet to take ownership of the terminal while the contents of it are being executed. This means the output won't be displayed inside the presentation but instead the presentation will pause, invoke the code snippet, and resume after the snippet is done. This is useful when running TUIs as otherwise those won't run given the terminal is taken by presenterm already.
Fixes #365
=> feat: allow acquiring terminal when running snippets

src/processing/builder.rs, src/processing/code.rs, src/processing/execution.rs, src/render/highlighting.rs
This renames the `no_margin` attribute added in #363 to `no_background` and makes it do everything `no_margin` did but also prevents presenterm from adding a background to the snippet. This currently doesn't play well with `exec_replace` or `exec` meaning the snippet execution output still gets background. I will address this separately as there's other things I want to get to but I want to close this issue.
The following
~~~markdown
```text +no_background
.__    .__
|  |__ |__|   _____   ____   _____
|  |  \|  |  /     \ /  _ \ /     \
|   Y  \  | |  Y Y  (  <_> )  Y Y  \
|___|  /__| |__|_|  /\____/|__|_|  /
\/           \/             \/
```
~~~
Currently renders like this after this change:
Fixes #349
=> feat: add no_background property

executors.yaml
The default seems to be release mode which will slow down compilation unnecessarily and is inconsistent with `rust` which uses `cargo run` which uses debug mode by default.
=> chore: use debug mode in rust-script snippets

src/processing/builder.rs, src/processing/execution.rs, src/style.rs
This changes `+acquire_terminal` snippets so they can only be run a single time and adds the bar below them like in normal snippets. This lets you know they're executable and whether they've been run or not.
PS: this whole code execution displaying thing needs some refactoring
Fixes #374
=> feat: run acquire-terminal snippets a single time

src/execute.rs, src/processing/builder.rs, src/processing/execution.rs
=> fix: respect `+no_background` on a `+exec_replace` block

Cargo.lock, Cargo.toml, src/markdown/html.rs, src/markdown/mod.rs, src/markdown/parse.rs, src/render/engine.rs, src/style.rs
This PR adds support to parse inline span html tags and the `color` and `background-color` CSS attributes in the `style` span tag attribute. 
The `color` and `background-color` can have any `#RRGGBB` formatted color + any color like `red`, `dark_red`, etc, as used in themes.
For now this only supports "strict" mode in which any deviation from what's supported will raise an error. In another PR I will add a way to configure this flag so if you don't feel like erroring, you can disable it.
After this change, the following:
~~~markdown
Paragraphs can <span style="color: #ffff00">**mix** colors <span style="background-color: white">in any way</span>
* <span style="color: red">this is red</span>
* this has <span style="background-color: blue">blue background</span>
~~~
Renders as:
Fixes #88
=> feat: parse inline span tags and css color attributes in them

executors.yaml
Thanks for this awesome project! If it's welcome, I added [R](https://www.r-project.org/) support to the executors. I've only tested this locally but it seems to work nicely.
[Rscript](https://search.r-project.org/R/refmans/utils/html/Rscript.html) is a command-line tool that's installed along with R, and should behave in a way that's compatible with your approach.
=> Add R to executors

src/processing/builder.rs
=> fix: ignore comments that start with `vim:` prefix

executors.yaml
Closes #398.
To test:
```csharp +exec
// ignore
System.Console.WriteLine("Hello from C#");
```
=> Add C# to code executors

executors.yaml, src/ansi.rs
This forces color output when running rust, c, and c++ code snippets and a compilation error is found. e.g. 
Fixes #400
=> feat: force color output in rust, c, and c++ compiler executions

Cargo.lock, Cargo.toml, src/custom.rs, src/media/emulator.rs, src/media/kitty.rs, src/media/mod.rs, src/media/query.rs
This PR adds support for kitty protocol detection when you're using tmux. This means now when you're running tmux inside kitty you no longer need to explicitly configure the image protocol to be kitty-local/remote and it will be instead figured out automatically.
This is done by making two kitty graphics protocol queries (and for local and one for remote support) and another widely supported query just in case the emulator doesn't support the kitty protocol and ignores our queries (this is what's suggested [here](https://sw.kovidgoyal.net/kitty/graphics-protocol/#querying-support-and-available-transmission-mediums)). The [third query](https://vt100.net/docs/vt510-rm/DA1.html) being done gets us the terminal capabilities; we figure out whether we support sixel by parsing its output. This …
=> feat: detect kitty through tmux

src/media/emulator.rs
This detects ghostty and uses the kitty graphics protocol on it by default. I don't have access to ghostty yet so I can't test this but based on [this article](https://fredrikaverpil.github.io/blog/2024/12/04/ghostty-on-macos/) `TERM_PROGRAM=ghostty` is the way to detect this. If it implements the protocol correctly, this should work out of the box.
@fredrikaverpil could I ask for your help here? :)
=> feat: use kitty image protocol in ghostty

config-file-schema.json, src/config.rs, src/demo.rs, src/main.rs, src/presenter.rs, src/render/engine.rs, src/render/mod.rs, src/render/validate.rs
This adds a `defaults.max_columns` property in the config file that allows specifying the maximum number of columns you want the presentation to take up. This means if `columns > max_columns`, the presentation will be capped to `max_columns` and the entire presentation will be centered with the remainder of the size being spread equally on both sides of the presentation.
Fixes #410
=> feat: allow capping max columns on presentation

config-file-schema.json, src/code/snippet.rs, src/config.rs, src/main.rs, src/presentation/builder.rs
This adds a new `auto_render_languages` [option](https://mfontanini.github.io/presenterm/guides/configuration.html#options) (meaning it can be configured in the config file or in the presentation itself) that specifies a list of languages for which the `+render` attribute is implied and are therefore automatically rendered. This means for example this presentation would have its mermaid diagram automatically rendered as an image:
~~~markdown
---
options:
auto_render_languages:
- mermaid
---
```mermaid
sequenceDiagram
bob ->> mike: oh hi
```
~~~
Fixes #416
=> feat: allow auto rendering code snippets

src/terminal/emulator.rs
I noticed somehow this was thinking I was in xterm when using ghostty. This moves the detection of emulators based on `TERM_PROGRAM` up before anything else.
=> fix: check for `TERM_PROGRAM` before `TERM` to determine emulator

src/config.rs
It looks like mac and windows can't bind to 127.255.255.255, whereas this works in linux. For now those 2 will bind to 127.0.0.1, which means you won't be able to run more than one presentation using speaker notes at the same time, which is anyway something that should never happen in practice.
=> fix: udp socket bind issues in windows/mac

Cargo.lock, Cargo.toml, src/markdown/elements.rs, src/markdown/parse.rs
This bumps dependencies and luckily comrak fixed the source position bug where the front matter's lines weren't being taken into account so the workarounds here go away.
=> chore: bump dependencies

src/markdown/elements.rs, src/markdown/parse.rs, src/presentation/builder.rs, src/theme.rs, src/ui/footer.rs, themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml, themes/catppuccin-mocha.yaml, themes/dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
This adds supports for markdown alerts (github/gitlab style) as support for these was recently added to comrak. This for now looks close a block quote except it also contains a title colored the same color as the vertical bar prefix that shows up on the left of the block quote.
See https://github.com/kivikakk/comrak/pull/519 and https://github.com/kivikakk/comrak/pull/521 for syntax but basically this:
```markdown
> [!note]
> this is a note
> [!tip]
> this is a tip
> [!important]
> this is important
> [!warning]
> this is warning!
> [!caution]
> this advises caution!
>>> [!note] other title
ez
multiline
>>>
```
Renders like this:
=> feat: add markdown alert support

Cargo.lock, Cargo.toml, src/commands/speaker_notes.rs, src/config.rs, src/main.rs
This makes:
* Linux bind to 127.0.0.1 and publish on 127.255.255.255 which allows multiple listeners on the same port as expected.
* Windows bind and publish on 127.0.0.1, which also allows multiple listeners.
* Mac's lo interface doesn't have `BROADCAST` enabled, so binding multiple listeners is not supported since while we could allow binding multiple listeners, only one of them would get the packets so instead we err. Maybe there's a better way of doing this but in practice nobody's going to be running multiple presentations at once so making this more complicated provides no gain.
=> fix: bind/publish to different addresses in non linux

src/markdown/text_style.rs, src/presentation/builder.rs, src/render/mod.rs, src/render/text.rs, src/terminal/image/printer.rs, src/terminal/image/protocols/ascii.rs, src/terminal/image/protocols/kitty.rs, src/terminal/printer.rs, src/theme.rs, themes/dark.yaml
This allows defining a color palette in themes, which allows reusing colors across the theme and in html span tags. In particular in theme files there's always the same set of colors used all over the place, and it's annoying to have to always address them using a RGB hex spec. This instead allows defining a set of named colors and then those colors can be referenced where a color would be used (e.g. in a theme or in a span tag) by using the `palette:<name>` or `p:<name>` syntax.
For the color name this uses a stack allocated string of at most 16 characters. This is not an optimization but a workaround since `Color`, `Colors` and `TextStyle` are currently `Copy` and using a `String` would make them non copy which would involve changing lots of code. This constraints the length of the …
=> feat: add color palette in theme to allow reusing colors

src/presentation/builder.rs
This is a followup on #427 which didn't consider styled text inside a block quote.
=> fixup: support colors in block quotes

.github/workflows/merge.yaml, src/code/snippet.rs, src/presentation/builder.rs, src/theme.rs, src/ui/execution.rs, src/ui/footer.rs, themes/dark.yaml
This is a follow up on #423 that adds symbols before the title of alert type elements. The structure of the theme changed a bit to be able to pack the styles for each alert type into a single type.
This causes the following presentation:
```markdown
> [!note]
> this is a note
> [!tip]
> this is a tip
> [!important]
> this is important
> [!warning]
> this is warning!
> [!caution]
> this advises caution!
>>> [!note] other title
ez
multiline
>>>
```
To render like this:
=> feat: add symbols to alerts

src/config.rs, src/demo.rs, src/main.rs, src/markdown/text.rs, src/markdown/text_style.rs, src/presentation/builder.rs, src/render/engine.rs, src/render/text.rs, src/terminal/capabilities.rs, src/terminal/emulator.rs, src/terminal/mod.rs, src/terminal/printer.rs, src/theme.rs, themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml, themes/catppuccin-mocha.yaml, themes/dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
This adds support for kitty's font size protocol (https://github.com/kovidgoyal/kitty/issues/8226) which allows printing characters that take up more than one cell. This feature will be available in kitty >= 0.40.0 and is currently only available in nightly builds.
This for now is only supported in a subset of the theme components, namely:
* The introduction slide's presentation title (`intro_slide.title.font_size`).
* The slide titles (`slide_title.font_size`).
* The headings (`headings.h*.font_size`).
Font sizes are only used if the terminal emulator supports it so this doesn't change anything for emulators other than kitty (or other implementors of the protocol). If you find this somehow breaks something, please create an issue.
For now all built in themes set …
=> feat: add support for kitty's font size protocol

src/theme.rs, src/ui/footer.rs
This sanitizes the theme footer's template so that we have sure that it's not malformed and doesn't reference any variables that can't be used (e.g. `{bar}`). This now also avoids allocation a bunch of strings when rendering the footer, since every variable was being replaced via `str::replace`.
This is a breaking change for anyone who already has a malformed string in their string templates. If someone does use a string like `{lord} George` in their footer please bring it up and we can see what to do.
=> feat!: sanitize theme footer's templates

src/demo.rs, src/main.rs, src/presentation/builder.rs, src/presenter.rs, src/render/engine.rs, src/render/mod.rs, src/render/operation.rs, src/render/text.rs, src/terminal/printer.rs, src/ui/modals.rs
This refactors the `Terminal` code a bit to be able to test it, and add tests to layout handling since the implementation for #437 will require creating new rect to print the images in.
=> chore: restructure `Terminal` code and add test for margins/layouts

src/demo.rs, src/export.rs, src/presentation/builder.rs, src/presenter.rs, src/render/engine.rs, src/render/operation.rs, src/render/properties.rs, src/resource.rs, src/terminal/image/scale.rs, src/third_party.rs, src/ui/execution.rs, src/ui/modals.rs
Images looked a little squashed vertically if the font being used in the terminal didn't have a 2:1 ratio between between columns and rows. This also adds some much needed tests around this code, and fixes some rounding issues when the image is small enough to only need a handful of columns/rows to be displayed.
Fixes #445
=> fix: don't squash image if font is not 2:1

src/demo.rs, src/export.rs, src/main.rs, src/presentation/builder.rs, src/render/engine.rs, src/render/operation.rs, src/resource.rs, src/terminal/emulator.rs, src/terminal/image/printer.rs, src/terminal/image/protocols/iterm.rs, src/terminal/image/protocols/kitty.rs, src/theme.rs, src/third_party.rs, src/ui/footer.rs
This allows using images in a footer template. For now they can only be used in the left and center templates by using this syntax:
```yaml
footer:
style: template
left:
image: path-to-image
height: 3
```
Images will preserve aspect ratios and will expand to take up as much of the `height` attribute as possible. Therefore, to scale images, simply bump that number up/down.
Images are looked up:
* Relative to the presentation's file, just like any other image.
* Inside the themes directory (~/.config/presenterm/themes).
Example using random logo:
Fixes #437
=> feat: support images in footer

Cargo.lock, Cargo.toml
Includes https://github.com/orhun/sixel-rs/pull/6 to fix build on aarch64 and riscv64.
If possible, please make a new release so downstream maintainers like Arch Linux RISC-V won't need to maintain this patch for an extended period. :P
=> chore: bump sixel-rs version

config-file-schema.json, src/config.rs
=> fix: don't err if auto_render_languages isn't set

src/code/snippet.rs, src/markdown/text.rs, src/presentation/builder.rs, src/render/engine.rs, src/render/layout.rs, src/render/text.rs, src/terminal/printer.rs
This extends the font size capabilities introduced in #438 by allowing the user to specify the font size in the form of a comment command anywhere in the presentation. This command changes the size of the font for the remainder of the slide.
Currently this doesn't work in cases like executable snippets, but I'll fix that when I have more time.
Example presentation:
~~~markdown
test
> this is
> small
test
> this is
> large
```rust
fn greet() -> &'static str {
"hi mom"
}
```
~~~
=> feat: allow specifying font size in comment command

src/markdown/elements.rs, src/markdown/parse.rs, src/presentation/builder.rs
This makes ordered lists that don't start at 1 to respect the number they're prefixed with. e.g.
```markdown
5. hi
6. mom
```
Will be now rendered as expected, whereas before it would show indexes 1. and 2. for each item.
Fixes #457
=> fix: respect lists that start at non 1 indexes

src/presentation/builder.rs, src/ui/execution.rs, src/ui/separator.rs
After #458 most components were allowed to have a font size except a couple. This expands that list to include code execution components (the separator bar and the output).
This code has turned quite gore after all these changes and will be refactored soon. Markdown tables still don't respect the font size but that should hopefully be easier after the refactor.
=> feat: set font size on code execution components

executors.yaml
=> fix: use right script name for kotlin files when executing

src/presentation/builder.rs, src/ui/footer.rs
This allows styling the template footer using markdown, including colors from the theme palette. If the front matter contains the `title` entry and that contains markdown, it is also rendered as expected.
Example:
~~~markdown
---
theme:
override:
footer:
style: template
left: "_how_ to <span style=\"color: red\">chop</span> **onions**"
---
~~~
=> feat: allow footer to be styled via markdown

src/markdown/parse.rs, src/theme/raw.rs, src/ui/footer.rs
After #442 you could no longer use braces unless it was to refer to a variable. This PR softens that restriction by letting you use double braces as an "escaped brace" to let you use them anywhere.
e.g. this footer "{title} {{potato}}" will render as "<title> {{potato}}"
=> feat: allow escaped braces in footer

src/markdown/html.rs, src/markdown/text_style.rs, src/theme/clean.rs, src/theme/raw.rs, src/ui/footer.rs
This introduces a `palette.classes` entry in the theme that allows defining a class (a background and foreground color pair). This can then be referenced when using spans by using the `class` html attribute.
As an example. the following presentation:
~~~markdown
---
theme:
override:
palette:
classes:
bokita:
foreground: yellow
background: dark_blue
footer:
style: template
left: "<span class=\"bokita\">hello</span>"
---
hi <span class="bokita">hello</span>
~~~
Renders liks:
=> feat: introduce `palette.classes` and use span.class to reference it

config-file-schema.json, src/config.rs, src/main.rs, src/presenter.rs, src/render/engine.rs, src/render/mod.rs
This introduces a new `defaults.max_columns_alignment` that can have values `left`, `center`, and `right`. This works along with `max_columns` and allows specifying how to align the presentation if the terminal size is greater than it. Before this change, this would behave like `max_columns_alignment: center` does now so that's the default if not set.
e.g. setting this to `left` will cause look like this on a wide terminal:
=> feat: allow configuring alignment when max columns is hit

src/ui/footer.rs
This otherwise causes footers with tall images that need `footer.height` adjusted to have the text too far down.
=> chore: move footer up depending on footer height

src/presentation/builder.rs
Changing attributes like `+line_numbers` wasn't causing the code's slide to be jumped-to.
=> fix: jump to right slide on code attribute change

themes/gruvbox-dark.yaml
This PR adds a [gruvbox](https://github.com/morhetz/gruvbox) theme to presenterm.
=> Add gruvbox dark theme

src/code/snippet.rs, src/presentation/builder/mod.rs, src/presentation/builder/snippet.rs, src/theme/clean.rs, src/ui/execution.rs
This mostly moves the snippet processing to a separate module to remove the noise in `builder.rs`.
=> chore: refactor snippet processing

themes/terminal-dark.yaml, themes/terminal-light.yaml
For some reason terminal-light and terminal-dark were using bright background/text in snippet execution outputs.
=> fix: snippet execution output colors in terminal-* themes

src/main.rs
The new `--current-theme` switch will print the theme in use to stdout. This will be the configured theme in the config file, if set, or the default theme as a fallback.
Relates to #488
=> feat: add `--current-theme` to display the theme in use

src/presentation/builder/mod.rs
This causes end slide shorthands to be respected when in speaker notes mode.
This speaker notes/presentation mode code needs some splitting, this currently makes it hard to know what needs to be done / is done in each case. But this does for now.
Fixes #491
=> fix: respect end slide shorthand in speaker notes mode

Cargo.lock, Cargo.toml, src/markdown/elements.rs, src/terminal/ansi.rs
Changes in 0.10.0 were made to fix some incorrect ansi escape code parsing when processing snippet execution output. However, those changes were still not handling parsing properly and ended up causing it to break in other cases.
This change hopefully fixes that. This also removes ansi-parser and starts using vte to parse escape codes as ansi-parser doesn't let you have more than 5 segments in an escape code. As an added bonus this also removes a bunch of dependencies.
Fixes #499
=> fix: ansi escape code parsing

src/export/exporter.rs, src/export/pdf.rs
This respects font sizes in the generated PDF. The one thing that is not yet supported here is text with font size > 1 _and_ with a background color. The background color only shows up in the line where the text is. But this should be rarer (e.g. a font size > 1 code block?) so this works for most cases.
Fixes https://github.com/mfontanini/presenterm-export/issues/17
=> feat: respect font sizes in generated PDF

.github/workflows/merge.yaml, config-file-schema.json, src/config.rs, src/main.rs
This allows specifying the dimensions to use when exporting a presentation to PDF. This allows exporting to PDF in contexts without a tty which should help people write scripts that automatically export presentations. This now also adds a step in the CI that tries to export the default presentation as PDF, which couldn't be tested before because of the tty restriction.
```yaml
export:
dimensions:
rows: 35
columns: 135
```
=> feat: allow specifying export dimensions in config file

.github/workflows/nightly.yaml, .github/workflows/release.yaml
This causes builds to fail. This should maybe be moved to use some sixel crate that's pure rust and not based on libsixel.
=> ci: revert build with sixel enabled

src/export/exporter.rs, src/export/pdf.rs, src/main.rs
This adds a `--export-temporary-path` that allows using some specific path to store intermediate files used when exporting to pdf (currently an html and a css file) rather than using a temporary path. This helps debugging #516 but is also generally useful.
=> chore: allow specifying path for temporary export files

src/export/html.rs, src/export/mod.rs, src/export/pdf.rs, src/markdown/text_style.rs
This cleans up the code around text attributes and adds more tests when converting text to html. This will simplify exporting as HTML in the near future.
=> chore: cleanup text attributes

src/presentation/builder/mod.rs
This is fragile and broke after #512, eventually it should be cleaned up so this can't break as easily.
=> fix: display inline code colors when in list

src/export/exporter.rs, src/main.rs
Adds a new command-line option (`--output`/`-o`) allowing users to specify custom output paths when exporting presentations to PDF. Previously, presenterm automatically generated PDFs in the same location as the input file.
This feature simplifies multi-theme exports without requiring manual file renaming or temporary copies. It enables clean parallel exports with different themes (light/dark) to distinct output files.
```bash
generate_pdf() {
local dir="$1"
local theme="$2"
cd "$dir" || exit
"$PRESENTERM_PATH" -e -t "$theme" --export-temporary-path "$TEMP_DIR" slide.md
mv slide.pdf "slide_${theme}.pdf"
cd - >/dev/null || exit
}
```
```bash
generate_pdf() {
local dir="$1"
local theme="$2"
cd "$dir" || exit
"$PRESENTERM_PATH" -e -t "$theme" --output "slide_${theme}.pdf" slide.md
cd - …
```
=> feat: add --output option for PDF exports

config-file-schema.json, src/config.rs, src/main.rs, src/presenter.rs, src/render/engine.rs, src/render/mod.rs, src/render/properties.rs, src/render/text.rs, src/terminal/image/printer.rs, src/terminal/printer.rs, src/terminal/virt.rs, src/transitions/mod.rs, src/transitions/slide_horizontal.rs
This adds support for the first slide transition animation that swaps between slides horizontally. This is still a work in progress; it's functional but is missing a few things like dealing with images. The configuration currently looks like the following, but it will likely be changed slightly once another type of transition is supported (will happen before next release).
```yaml
transition:
duration_millis: 750
animation:
style: slide_horizontal
```
This looks like the following:
https://github.com/user-attachments/assets/9475caf9-0538-4ffd-8858-115aac348bd1
Relates to #364
=> feat: add slide horizontally slide transition animation

src/render/engine.rs, src/render/text.rs, src/terminal/printer.rs, src/terminal/virt.rs, src/transitions/mod.rs
This was needed at some point because of how text styling worked but it's no longer the case.
=> chore: get rid of `TextProperties`

src/export/pdf.rs, src/presenter.rs, src/render/engine.rs, src/render/text.rs, src/terminal/image/printer.rs, src/terminal/image/protocols/ascii.rs, src/terminal/image/protocols/iterm.rs, src/terminal/image/protocols/kitty.rs, src/terminal/image/protocols/sixel.rs, src/terminal/printer.rs, src/terminal/virt.rs
This includes images when transitioning between slides; this was the one detail remaining after #528. This could probably be made a bit more efficient as it currently causes us to potentially read the image from disk and decode it. In practice I don't know if it matters though so I'd rather have this merged now and look at optimizations in the future if needed.
In this implementation, images are turned into ascii via the ascii printer and that is used during the transition. I don't think it's viable/makes sense to print the actual image that many times just for the transition.
Relates to #364
https://github.com/user-attachments/assets/1f5d13df-d928-4789-87ee-b73824728609
=> feat: include images in slide transitions

config-file-schema.json, src/config.rs, src/main.rs, src/presenter.rs, src/render/engine.rs, src/render/mod.rs, src/render/text.rs, src/terminal/image/printer.rs, src/terminal/image/protocols/ascii.rs, src/terminal/image/protocols/kitty.rs, src/terminal/image/scale.rs, src/terminal/printer.rs, src/terminal/virt.rs
Similar to `max_columns` this adds a `max_rows` and `max_rows_alignment` (valid values are `top`, `center`, `bottom`, the default is `center`) that cap the vertical presentation size and aligns it accordingly.
=> feat: add `max_rows` configuration to cap vertical size

src/presentation/builder/mod.rs
The absolute path to the temporary directories has been replaced with the path specified in the environment variables.
=> fix: fixing the external_snippet test error

config-file-schema.json, src/config.rs, src/export/pdf.rs, src/presenter.rs, src/terminal/virt.rs, src/transitions/fade.rs, src/transitions/mod.rs, src/transitions/slide_horizontal.rs
This adds another animation: `fade`. This essentially draws the new slide on top of the current one by jumping to cells that have changed between slides randomly and printing their contents.
https://github.com/user-attachments/assets/eb2d7d68-9967-4855-a06b-cbe208b21c6f
Fixes #364
=> feat: add fade slide transition

themes/terminal-dark.yaml, themes/terminal-light.yaml
This sets no background for typst renders in the terminal-light and terminal-dark built in themes. This requires a reasonably recent version of typst (probably 0.12+) as they changed the meaning of `none` as a fill background at some point around then.
=> fix: use no typst background in terminal-* built in themes

src/render/engine.rs, src/render/text.rs
This fixes an issue where centered text that overflowed had the lines 2+ start at the same column as the first one rather than being centered.
Fixes #545
=> fix: center overflow lines when using centered text

Cargo.toml, src/main.rs, src/presentation/builder/mod.rs, src/presenter.rs, src/resource.rs, src/terminal/image/printer.rs, src/terminal/image/protocols/ascii.rs, src/terminal/image/protocols/iterm.rs, src/terminal/image/protocols/kitty.rs, src/terminal/image/protocols/sixel.rs, src/terminal/virt.rs, src/third_party.rs, src/ui/execution.rs
This caches:
* Ascii images so we don't reload them every time we're doing slide transitions.
* Ascii image resizes, so if we go to a slide that contains an image and we're using slide transitions, the next transition that includes that image won't require resizing it to that same sizes.
The one performance "issue" still present when using slide transitions is that we still need to pay for that first image -> ascii image conversion and that first ascii image resize the first time we transition to a slide that contains an image. This is currently noticeable in debug mode and not in release mode (at least in my machine ™️), but it would be sweet if it wasn't there ever. For this we need to run through all slides, find all images, ascii convert them and resize them to the current terminal …
=> perf: cache resized ascii images

src/presenter.rs, src/render/ascii_scaler.rs, src/render/mod.rs, src/terminal/image/protocols/ascii.rs
This pre-scales images when the presentation is reloaded and transitions are enabled. For now only filesystem images are scaled but the next PR will do this for generated ones as well. The end result of this is when you transition between slides and there's images in them, the animation is smooth the first time because the scaling, which is costly, is done ahead of time.
=> perf: pre-scale ascii images when transitions are enabled

src/export/pdf.rs, src/presentation/mod.rs, src/presenter.rs, src/render/ascii_scaler.rs, src/render/engine.rs, src/resource.rs, src/terminal/image/mod.rs, src/terminal/image/printer.rs, src/terminal/image/protocols/ascii.rs, src/terminal/printer.rs, src/terminal/virt.rs
Before this change only filesystem images were scaled when transitioning between slides. This PR does that for generated images as well, and polls other slides while doing transitions so any images generated asynchronously are already ASCII'd before we transition into them.
This PR has shown that the async render code has reached proper :hankey: level and requires changing it, more so since #537 will be implemented soon-ish.
=> perf: pre scale generated images

src/render/engine.rs, src/render/operation.rs, src/theme/clean.rs, src/theme/raw.rs, src/ui/footer.rs, src/ui/modals.rs
This adds support for footer images on the right, just like allowed for left/center. Now that there's tests for this and after being restructured fairly recently it's much easier to get _right_.
The following presentation now renders like the following:
```markdown
---
theme:
override:
footer:
height: 5
style: template
left:
image: ../examples/doge.png
center:
image: ../examples/doge.png
right:
image: ../examples/doge.png
---
Footer images
===
```
Closes #549
=> feat: allow using images on right in footer

config-file-schema.json, src/config.rs, src/export/exporter.rs, src/main.rs, src/presentation/builder/mod.rs, src/presentation/mod.rs
This introduces the config property `export.pauses` which when defaults to `ignore` but when set to `new_slide` causes the PDF export to contain a new slide every time a pause is found.
Closes #555
=> feat: allow letting pauses become new slides when exporting

config-file-schema.json, src/config.rs, src/presenter.rs, src/transitions/collapse_horizontal.rs, src/transitions/mod.rs, src/transitions/slide_horizontal.rs
This adds a new `collapse_horizontal` slide transition that collapses the current slide into the center of the screen.
https://github.com/user-attachments/assets/a398c286-ae3e-4c99-81aa-26aba498726d
=> feat: add `collapse_horizontal` slide transition

Cargo.lock, Cargo.toml, scripts/validate-config-file-schema.sh, src/code/snippet.rs, src/commands/keyboard.rs, src/config.rs, src/main.rs, src/theme/raw.rs, src/utils.rs
This hides the JSON schema generation for the config file behind a new `json-schema` feature flag. This is not fundamental to the functioning of this tool and also there's already a schema generated [here](https://github.com/mfontanini/presenterm/blob/master/config-file-schema.json) so there's no need to have this available in the tool when released. If anyone does want the JSON schema for some specific version of the tool, they can always clone the repo and `cargo run --features json-schema`.
This also removes the `serde_with` dependency and instead hand rolls the `SerializeDisplay` and `DeserializeFromStr` macros manually. These are very few lines long and doesn't make importing that crate worth it.
Overall these 2 changes cause the number of crates to go down by something like 20 which …
=> feat!: hide JSON schema generation behind feature flag

src/code/snippet.rs, src/presentation/builder/snippet.rs
This adds new optional `start_line` and `end_line` properties when using a `file` type snippet, which allow specifying the line range to be used.
Caveats:
* The line selection is applied before highlighting so if you truncate the file in a place that should be highlighted in some way because of something that came before (e.g. multi line comments) it won't be highlighted appropriately. This can be fixed but requires changing a few things and I think this should not be hit very often.
* Using `+line_numbers` will always start at 1. In the future I may add a property like `preserve_line_numbers` but again this would require changing a few things (the same ones as the point above) so I kept it this way for now.
Example:
~~~markdown
```file +line_numbers
language: rust
path: scripts/foo.rs …
```
=> feat: allow specifying start/end lines in file snippet type

docs/src/configuration/introduction.md
Rename `--config-path` in configuration/introduction section to `--config-file`
=> fix: Rename parameter name to the correct one in docs

.github/workflows/merge.yaml, src/export/output.rs, src/main.rs, src/terminal/image/mod.rs, src/terminal/image/printer.rs, src/terminal/image/protocols/ascii.rs, src/terminal/image/protocols/mod.rs, src/terminal/image/protocols/raw.rs, src/terminal/mod.rs
#566 did the heavy work to allow HTML exports but the one thing missing is that images were still referenced on their external paths, which caused 2 issues:
* Files were not redistributable unless you included images and fixed their paths.
* Generated images (e.g. mermaid diagrams) were likely pointing to a temporary directory so they'd be lost.
This changes that so HTML exports are now fully self contained, using `data:...` notation to inline images within the HTML.
=> feat: make HTML export self contained

src/export/exporter.rs, src/render/operation.rs, src/ui/execution/snippet.rs
A recent refactoring on snippet execution caused a disconnect between a snippet being executed and how it reflected its state on the shared types between the snippet and the component that polls it. This caused PDF exports that contained more than one executable snippet to only have its first snippet executed and the rest still shown as "running".
Addresses part of #582
=> fix: execute snippets only once during export

config-file-schema.json, src/config.rs, src/export/exporter.rs, src/main.rs
This adds a new attribute `export.snippets` in the config file that configured how executable snippets are handled when exporting PDFs/HTMLs. By default it uses `parallel` meaning all snippets are ran at the same time, whereas `sequential` means only one snippet will be ran at a time. This can help handle cases were snippets have to be ran sequentially because the output of snippet N depends on the output of snippet M < N.
Example config:
```yaml
export:
snippets: sequential
```
Closes #582
=> feat: allow configuring sequential executable snippet processing

docs/src/features/code/highlighting.md
Single word change on line 150: `s/shot/show`
Thanks!
=> Fix typo in highlighting.md

src/presentation/builder/snippet.rs, src/theme/clean.rs, src/theme/raw.rs, src/ui/execution/snippet.rs, themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml, themes/catppuccin-mocha.yaml, themes/dark.yaml, themes/gruvbox-dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
This adds a new `execution_output.padding` option in the theme that behaves just like `code.padding`. Built in themes now all have this property set to be the same as the `code.padding` (2 horizontal, 1 vertical padding) because I think it looks better. Please chime in if anyone doesn't feel like this is the case though!
Closes #591
=> feat: add padding to execution output

src/ui/execution/snippet.rs
This changes the new behavior on #592 so no padding is added if there's no output.
=> chore: don't show execution output padding if there's no output

src/export/output.rs
Without this safari shows crap on non ascii characters
=> fix: use charset in output HTML

src/export/html.rs, src/markdown/parse.rs, src/markdown/text_style.rs, src/terminal/capabilities.rs, src/terminal/printer.rs
This adds support for superscripts via `x^42^` syntax. This requires the terminal to support half sizes (`n=X:d=Y`) via the kitty font size protocol. This works _okay_ in PDF/HTML exports, except when using superscripts in block quotes. In that case it looks a bit messed up. It's possible there's other places where it also looks bad (now typing this, alerts are also affected).
This is using half blocks but also still making them take up an entire cell. There's a way around this but requires changing a few things so I'd rather have something functional for now that can be iterated on.
Relates to #604
=> feat: support superscript via kitty font size protocol

config-file-schema.json, executors.yaml, src/code/execute.rs, src/code/snippet.rs, src/config.rs, src/presentation/builder/mod.rs, src/presentation/builder/snippet.rs, src/ui/execution/acquire_terminal.rs, src/ui/execution/image.rs, src/ui/execution/snippet.rs
This adds support for alternative snippet executors for an already executable language. This allows, for example, executing a rust snippet using something other than the default way of execution (e.g. via `rust-script`).
See executors.yaml changes for config but essentially, a new `alternative` map can be defined under each language that contains the same parameters as the normal executor attribute.
To use alternative executors use the syntax `+exec:<name>` for normal execution, `+exec_replace:<name>` for exec replace and `+acquire_terminal:<name>` for acquire terminal execution type. For example, the following uses rust-script:
~~~markdown
```rust +exec:rust-script
fn foo() { .... }
// ....
```
~~~
Closes #603
=> feat: allow alternative snippet executors for supported langs

.github/workflows/merge.yaml, flake.lock, flake.nix, src/code/padding.rs, src/export/html.rs, src/markdown/parse.rs, src/presentation/builder/mod.rs, src/terminal/ansi.rs, src/terminal/image/protocols/ascii.rs, src/ui/execution/snippet.rs, src/ui/modals.rs
Rust 1.82 came out 7 months ago, it's about time to upgrade. This fixes clippy lints that required that version to be used.
=> chore: bump rust version to 1.82

src/markdown/elements.rs, src/markdown/parse.rs, src/presentation/builder/mod.rs
This adds support for markdown footnotes. Footnotes are written where they show up, as is. Example:
```
foo![^1] and bar[^2]
[^1]: hi
[^2]: bye
```
Closes #604 
PS: this requires the kitty font size protocol. In another PR I'll add something to use unicode half characters as fallback where possible.
=> feat: add support for footnotes

src/terminal/capabilities.rs
This was reported as part of #619, although not the original issue.
=> fix: don't loop on 0 bytes read when querying capabilities

config-file-schema.json, src/config.rs, src/main.rs, src/presentation/builder/mod.rs
This adds a new comment command `list_item_newlines` which is also configurable via `options.list_item_newlines` in the config file/presentation front matter. This option allows configuring the number of newlines in between list items (defaults to 1):
```markdown
* hi
* inner
* bye
---
* hi
* inner
* bye
```
Closes #626
=> feat: allow configuring number of newlines in between list items

config-file-schema.json, src/code/snippet.rs, src/config.rs, src/main.rs, src/presentation/builder/mod.rs, src/presentation/builder/snippet.rs, src/ui/execution/mod.rs, src/ui/execution/validator.rs
This adds a `--validate-snippets` cli arg and a config option `snippets.validate` that allow configuring whether snippets should be validated. This causes presenterm to execute snippets on load and every time the presentation is modified, and ensure the snippet execution returns a 0 status code. The snippets can also now contain a `+validate:fail` or `+validate:failure` that indicate the expected validation output should be an error. e.g. if you expect a snippet to fail because it contains a syntax error, you can use this to annotate it accordingly and ensure it fails.
Note that this isn't done for `+acquire_terminal` snippets because they'd otherwise take over the terminal.
[![asciicast](https://asciinema.org/a/URm4c8QhLAnnoxKc218fN6FyY.svg)](https://asciinema.org/a/URm4c8QhLAnnoxKc218fN6 …
=> feat: allow validating snippets

src/markdown/text.rs, src/render/mod.rs, src/terminal/ansi.rs, src/ui/execution/snippet.rs
Before this change we were applying a 25% horizontal margin to all runtime errors (e.g. image doesn't exist), which caused errors to look bad, especially if the terminal size was small. This instead centers them which makes them look a lot better.
=> feat: center runtime errors

executors.yaml
This adds a new `rust-script-pedantic` alternative executor for rust. This is the same as `rust-script` but it passes `--deny warnings` to `rust-script` so any warnings are considered errors. This is useful when using `--validate-snippets` so you know there's no warnings nor errors in the snippets.
Relates to #639
=> feat: add `rust-script-pedantic` executor for rust

src/code/snippet.rs, src/presentation/builder/snippet.rs
This adds a `+validate` (also `+validate:<executor>`) that allows indicating that the snippet should be validated. This causes `--validate-snippets` to validate any snippet that's either `+exec` or `+exec_replace` or `+validate`.
This renames the `+validate` created in #637 that allows specifying whether the snippet should succeed or fail into `+expect`. e.g. `+expect:failure` means "this snippet should fail when being validated".
Closes #643
=> feat: allow validating snippets without executing them in presentation

docs/src/features/exports.md
[uv](https://github.com/astral-sh/uv) is a cool project also made in rust where you can run command with a python dependency without the need of a `pyproject.toml` (see https://docs.astral.sh/uv/guides/scripts/#running-a-script-with-dependencies)
Add a note for exporting pdf using it
=> Add a note to export pdf using `uv`

src/demo.rs, src/export/exporter.rs, src/presentation/builder/mod.rs, src/presenter.rs
This paves the way for #552 to be implemented. Essentially the presentation builder now takes markdown, which allows it to parse it and in the future parse other markdown chunks loaded from other files without having a weird mixed API. 
As part of this all builder tests were changed to take markdown as input, which makes them much more concise.
=> chore: allow presentation builder to take markdown as input

src/presentation/builder/mod.rs, src/presentation/builder/snippet.rs, src/resource.rs
This adds a new `include` comment command that allows including an external markdown file. The file is included as-is and mostly parsed as if it were part of the original markdown.
Example:
~~~markdown
hi
~~~
other.md:
~~~markdown
bye
~~~
The result will be a single slide that contains "hi" and "bye" each in a new line.
Notes:
* The file is parsed separately so no parsing state is shared between them. e.g. if you have an import like the following, where `other.md` contains the closing backticks, it won't work:
~~~markdown
```
~~~
* Errors are still not adapted to this multi markdown mode. That is, now if you have an error on some markdown file you'll see "error at 5:1" but you won't know the filename. This will be fixed separately in another PR that will come in soon (no energy left today …
```
=> feat: add `include` comment command to import markdown files

src/render/engine.rs
`max_rows` was essentially broken in #594 (released in 0.14.0).
Fixes #641
=> fix: consider rect start row when capping terminal rows

src/code/snippet.rs, src/presentation/builder/comment.rs, src/presentation/builder/error.rs, src/presentation/builder/mod.rs, src/presentation/builder/snippet.rs, src/presentation/builder/tests.rs, src/render/engine.rs, src/render/mod.rs, src/render/text.rs, src/terminal/ansi.rs, src/theme/clean.rs, src/ui/execution/snippet.rs
This adds a way of specifying where the output of an executable snippet will go, so it's not always shown right below the snippet. This can be useful in particular to place code in another column when the code itself is already long enough. To do this you need to:
* Create a `+exec` snippet and add a `+id:<name>` attribute.
* Add a comment command `snippet_output: <name>`. The output of the snippet will be placed here.
For example:
~~~markdown
```bash +exec +id:foo
echo "hello world"
echo "the time is $(date)"
```
~~~
Looks like:
The `+id` property may have more uses in the future but for now this is all it can be used for.
Closes #540
PS: this needs more testing and some better error reporting but I'm fried already.
=> feat: allow specifying where snippet output will go

executors.yaml, src/code/snippet.rs
With this you can use [uv](https://github.com/astral-sh/uvl) to execute python code by changing the language name to "uv". 
This calls `uv run --script -q (file)`. You can use the syntax for script dependencies:
```python
/// # /// script
/// # requires-python = ">=3.12"
/// # dependencies = [
/// #     "numpy",
/// # ]
/// # ///
import numpy as np
print("Hello from ts.py!")
```
and then use the triple slashes to hide it in the presentation.
=> Added uv as an executor for python code

Cargo.toml, docs/src/configuration/introduction.md, src/main.rs
I am kinda lazy and pretty forgetful so having to use ``--config-file`` to point to a local config file irks me.  
So this patch introduces a new env var: ``PRESENTERM_CONFIG_FILE``.    
``--config-file`` still has priority over the env var.
I use nix flakes a lot for working on projects (and I know others use ``direnv``) so this would allow for using a per project config file far easier.
I have tested it out locally and works pretty well
=> feat: allow using an ENV var to point to the config file

src/markdown/html.rs, src/markdown/parse.rs
This extends the superscript support added in #606 to also support `<sup>` tags.
=> feat: support parsing `sup` inline HTML tag

.github/workflows/nightly.yaml
This prevents the nightly job from running if the git hash hasn't changed, to prevent spending on (macOS) runners.
=> chore: don't run nightly job if the git hash hasn't changed

themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml, themes/catppuccin-mocha.yaml
Previously the colours were hard coded. This PR updates the themes to make use of palettes, which has the nice advantage of allowing these colours to be referred to by name in slides - and makes switching between the catppuccin themes more pleasant for the user.
Palettes have been built by referencing the [Catppuccin documentation](https://github.com/catppuccin/catppuccin).
Closes #673
=> Update Catppuccin themes to use palettes

src/presentation/builder/comment.rs, src/presentation/builder/error.rs, src/presentation/builder/mod.rs
This adds prettier errors by adding a context that displays the markdown file where the error was found. There's still a couple of error types that don't have this (and will soon) but for now any parse error or "general" presentation error will use this new format.
=> feat: add markdown context to errors

src/presentation/builder/intro_slide.rs, src/presentation/builder/mod.rs
This allows multiline slide titles by using markdown multiline syntax.
Example:
```markdown
---
title: |
My journey:
from `foo` to `bar`
---
```
Closes #670
=> feat: allow multiline slide titles

src/demo.rs, src/markdown/elements.rs, src/markdown/parse.rs, src/presentation/builder/heading.rs
`SetexHeading` is now a vector of lines, with an implicit line break between them, inserted by `push_slide_title`.  
I decided to only put the contents of the first exHeading line as the slide name(for the slides modal), as there is no solution that will fit all formatting(without any additional insertions, the words will be squished together, with any added characters, it will look weird if the writer already added one)
=> feat: add support for multiline slide titles

src/resource.rs
`include: <self>` would cause the presentation file to not be watched anymore :facepalm:
=> fix: don't remove watch to main presentation file

src/presentation/builder/comment.rs, src/presentation/builder/mod.rs
Improve #684 when using include + a layout without a `coumn`
=> fix: display right source line when using import + column layout

docs/src/configuration/settings.md
This adds docs for the missing `validate_overflows` config.
=> docs: document overflow validation

config-file-schema.json, src/commands/keyboard.rs, src/commands/listener.rs, src/config.rs, src/main.rs, src/presentation/builder/comment.rs, src/presentation/builder/mod.rs, src/presentation/diff.rs, src/presenter.rs, src/render/engine.rs, src/render/operation.rs, src/render/properties.rs, src/theme/clean.rs, src/theme/raw.rs, themes/catppuccin-frappe.yaml, themes/catppuccin-latte.yaml, themes/catppuccin-macchiato.yaml, themes/catppuccin-mocha.yaml, themes/dark.yaml, themes/gruvbox-dark.yaml, themes/light.yaml, themes/terminal-dark.yaml, themes/terminal-light.yaml, themes/tokyonight-storm.yaml
This adds a new keymap (uppercase `T`) that toggles a layout grid for column layouts. This causes a vertical line to show up  in between every column in a column layout, which can ease debugging the layout.
https://github.com/user-attachments/assets/c80fd9af-8917-418f-8c4f-a9cd96197120
Closes #707
Also closes #717 since this touched the same code.
=> feat: add keymap to toggle layout grid

src/presentation/builder/heading.rs
This changes the behavior when an explicit `font_size` is set and a heading other than a slide title is used, so that we only add a single extra line after the heading, rather than one line per font size (e.g. 3 lines for font size 3). This was a deliberate choice initially but I'm not exactly sure why. If this breaks someone's flow please comment here!
Closes #714
=> fix: don't add extra heading lines depending on font size

README.md, docs/src/features/images.md, examples/demo.md
Just a small patch to have the same lists of supported terminals in `docs/src/features/images.md`, `examples/demo.md` and `README.md`
=> docs: sync supported terminals

docs/src/features/commands.md, src/main.rs, src/presentation/builder/comment.rs, src/presentation/builder/mod.rs
This PR adds a new CLI option `--list-comment-commands` that outputs all available presenterm comment commands to stdout.
The intention is to enable external tools and editors (like vim with fzf) to:
- Use this output as a source for snippet generation
- Validate comment commands
- Provide better autocompletion and tooling support
- Made the `CommentCommand` enum accessible internally
- Added a `generate_samples()` method that creates example strings for all comment types
- Added the CLI flag `--list-comment-commands` that outputs each command on a separate line
```bash
presenterm --list-comment-commands
presenterm --list-comment-commands | fzf
:r !presenterm --list-comment-commands | fzf
```
Each command is output on its own line with appropriate default values:
```
...
```
This format …
=> feat: add --list-comment-commands CLI option

src/presentation/builder/comment.rs, src/presentation/builder/error.rs, src/presentation/builder/mod.rs
Using `export.pauses: new_slide` would cause the slide state to be tossed away, which meant any state (e.g. layout, font size, etc) before the pause was tossed away.
Closes #730
=> fix: keep state between pauses on pause-new-slide

src/code/snippet.rs, src/presentation/builder/mod.rs, src/presentation/builder/snippet.rs
This adds a new `+auto_exec` attribute to snippets which requires `exec_replace` permissions and is basically a `+exec` but it gets automatically executed on start without having to press `<c-e>`.
Note that permissions are a bit :hankey: now and I will soon change this to have 2 permissions: on-demand execution and automatic execution. But for now this works.
=> feat: add `+auto_exec` attribute to snippets

src/commands/keyboard.rs, src/commands/listener.rs, src/commands/speaker_notes.rs, src/presentation/builder/comment.rs, src/presentation/mod.rs, src/presenter.rs
This changes the speaker notes listener mode so it respects pauses.
This makes the following presentation work the following way from a speaker notes listener:
```markdown
title
===
I will talk about `foo`
I will talk about `bar`
other
```
[![asciicast](https://asciinema.org/a/KXmipmlok9T5RfYlW0Nqn2Trr.svg)](https://asciinema.org/a/KXmipmlok9T5RfYlW0Nqn2Trr)
Closes #543
=> feat: respect `pause` in speaker notes

src/presentation/builder/heading.rs, src/theme/clean.rs, src/theme/raw.rs
This allows configuring a `prefix` on slide titles, which essentially allows you to make a slide title have the same style as a heading, since this was the only thing missing:
```markdown
---
theme:
override:
slide_title:
prefix: "██"
alignment: left
font_size: 1
---
title
===
```
Closes #694
=> feat: allow setting prefix on slide titles

src/presentation/builder/heading.rs
This makes so `implicit_slide_ends` works as expected when `h1_slide_titles` is set.
Closes #754
=> fix: make `implicit_slide_ends` play well with `h1_slide_tiles`
